project_id = "auofttkyosgjhxcbhscw"

[functions.share-resolve]
verify_jwt = false

[functions.odoo-api]
verify_jwt = false

[functions.questionnaire-resolve]
verify_jwt = false

[functions.questionnaire-save]
verify_jwt = false