-- New Zealand – Visitor Visa — 30 FAQs
-- Source: content/service-library/nz-visitor-visa.json

UPDATE public.service_library
SET academy_metadata = jsonb_set(
  COALESCE(academy_metadata, '{}'::jsonb),
  '{faqs}',
  '[{"q":"Can we guarantee visitor visa?","a":"No. INZ decides each case individually."},{"q":"How much funds?","a":"Enough for trip duration—no fixed amount but must be credible."},{"q":"Can visitor work?","a":"No. Work not permitted on visitor visa."},{"q":"Can switch to student in NZ?","a":"Generally must apply from outside NZ—verify current rules."},{"q":"Reapply after refusal?","a":"Yes when circumstances improve."},{"q":"Invitation letter needed?","a":"Recommended for family visits."},{"q":"Processing time?","a":"Typically 3–6 weeks standard."},{"q":"Multiple entry?","a":"Officer decides visa conditions at approval."},{"q":"What is Description for this service?","a":"Visitor visa for tourism, visiting family/friends, or short business visits to New Zealand. Applied online via Immigration NZ."},{"q":"What is Eligible applicants for this service?","a":"Temporary visit purpose · Funds for trip · Strong ties to India · Health and character requirements"},{"q":"What is No work permitted for this service?","a":"Visitors cannot work or study long courses. Short recreational study may be permitted—verify rules."},{"q":"Important note on No work permitted?","a":"Visitors cannot work or study long courses. Short recreational study may be permitted—verify rules."},{"q":"What is Key authority for this service?","a":"Immigration New Zealand (INZ)"},{"q":"What is After approval for this service?","a":"Respect visa conditions and departure date. Overstay affects future NZ applications."},{"q":"Is Valid passport required?","a":"Valid passport is typically required."},{"q":"Is Clear visit purpose required?","a":"Clear visit purpose is typically required."},{"q":"Is Proof of funds required?","a":"Proof of funds is typically required."},{"q":"Is Strong ties to India required?","a":"Strong ties to India is typically required."},{"q":"Is Onward/return travel plans required?","a":"Onward/return travel plans is typically required."},{"q":"Is Health/character requirements required?","a":"Health/character requirements is typically required."},{"q":"Is Immigration history disclosed required?","a":"Immigration history disclosed is typically required."},{"q":"What is the Processing time?","a":"3–6w — Standard"},{"q":"What is the Government fee?","a":"NZD $341 — Online approx"},{"q":"What is the Our approval rate?","a":"73% — ~61% benchmark"},{"q":"What is the Required docs?","a":"9 — + ties evidence"},{"q":"What is the Consultancy fee?","a":"See fee tab — + govt only"},{"q":"What if the client has Weak ties to India?","a":"Employment letter, business, property, family proof"},{"q":"Why is Weak ties to India a problem?","a":"No employment, assets, or family obligations."},{"q":"What if the client has Insufficient funds?","a":"Bank history, ITR, sponsor letter"},{"q":"Why is Insufficient funds a problem?","a":"Cannot credibly fund trip."}]'::jsonb
),
updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000062';
