/** Search hints for WhatsApp helpline staff guide */
export const WHATSAPP_GUIDE_KEYWORDS = [
  "whatsapp",
  "helpline",
  "simulate",
  "mock",
  "meta",
  "webhook",
  "intake",
  "YES",
  "lead",
  "assign",
  "counselor",
  "as client",
  "restart",
  "secrets",
  "token",
  "sandbox",
  "inbound",
  "reply",
  "phase 0",
  "phase 1",
  "privacy",
  "forward",
  "fl menu",
  "student visa",
  "COUNSELOR",
  "ai counseling",
  "lead capture",
  "EDIT",
  "RESTART",
