import { breakdown, fee, na } from "./builders";
import type { GovtFeeBreakdownSource } from "./types";

const HOME_AFFAIRS = "https://immi.homeaffairs.gov.au/visas/getting-a-visa/fees-and-charges/current-visa-pricing";
const VFS_AU = "Varies by VAC (VFS Global) — typically AUD 20–80 service fee where biometrics collected";

export const AUSTRALIA_FEE_BREAKDOWNS: GovtFeeBreakdownSource[] = [
  breakdown(
    "b2000001-0001-4000-8000-000000000041",
    "Australia – Student Visa (Subclass 500)",
    "AUD",
    HOME_AFFAIRS,
    "Jul 2025",
    [
      fee("visa_application", "Student visa base application charge (primary)", {
        amount: 2000,
        currency: "AUD",
        unit: "per applicant",
        notes: "Subclass 500 · annual fee review 1 July",
      }),
      fee("dependent_adult", "Subsequent applicant 18+", {
        amount: 530,
        currency: "AUD",
        unit: "per dependent adult",
      }),
      fee("dependent_child", "Subsequent applicant under 18", {
        amount: 175,
        currency: "AUD",
        unit: "per dependent child",
      }),
      na("landing_rprf", "Landing fee", "Not applicable for temporary visa"),
      na("biometrics", "Biometrics (government)", "No separate DHA biometrics fee"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "AUD",
        unit: "per applicant",
        notes: VFS_AU,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable — OSHC required separately"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000042",
    "Australia – Visitor Visa (Subclass 600)",
    "AUD",
    HOME_AFFAIRS,
    "Jul 2025",
    [
      fee("visa_application", "Visitor visa application charge (tourist stream)", {
        amount: 200,
        currency: "AUD",
        unit: "per applicant",
        notes: "Offshore tourist stream · verify stream on pricing table",
      }),
      na("dependent_adult", "Family visitor", "Each applicant pays separately"),
      na("dependent_child", "Child visitor", "Same base charge per person"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("biometrics", "Biometrics (government)", "No separate DHA fee"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "AUD",
        unit: "per applicant",
        notes: VFS_AU,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000043",
    "Australia – Partner Visa (Subclass 820/801)",
    "AUD",
    HOME_AFFAIRS,
    "Jul 2025",
    [
      fee("visa_application", "Partner visa combined charge (820/801)", {
        amount: 9365,
        currency: "AUD",
        unit: "per applicant",
        notes: "Single combined charge for temporary + permanent stages",
      }),
      fee("dependent_child", "Dependent child included in application", {
        amount: null,
        currency: "AUD",
        unit: "per dependent child",
        notes: "Additional applicant charges apply — verify on pricing estimator",
      }),
      na("dependent_adult", "Secondary adult applicant", "Rare — usually separate partner application"),
      na("landing_rprf", "Landing fee", "Included in combined partner charge"),
      na("biometrics", "Biometrics (government)", "No separate DHA fee"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "AUD",
        unit: "per applicant",
        notes: VFS_AU,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not available"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000044",
    "Australia – Skilled Migration (Subclass 189/190/491)",
    "AUD",
    HOME_AFFAIRS,
    "Jul 2025",
    [
      fee("visa_application", "Skilled visa base charge (primary 18+)", {
        amount: 4910,
        currency: "AUD",
        unit: "per applicant",
        notes: "Subclass 189/190/491 primary",
      }),
      fee("dependent_adult", "Additional applicant 18+", {
        amount: 2455,
        currency: "AUD",
        unit: "per dependent adult",
      }),
      fee("dependent_child", "Additional applicant under 18", {
        amount: 1225,
        currency: "AUD",
        unit: "per dependent child",
      }),
      na("landing_rprf", "Landing fee", "Included in visa charge"),
      na("biometrics", "Biometrics (government)", "No separate DHA fee"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "AUD",
        unit: "per applicant",
        notes: VFS_AU,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not available"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000045",
    "Australia – Temporary Graduate Visa (Subclass 485)",
    "AUD",
    HOME_AFFAIRS,
    "Mar 2026",
    [
      fee("visa_application", "Temporary Graduate visa charge (primary)", {
        amount: 2300,
        currency: "AUD",
        unit: "per applicant",
        notes: "Post-1 Mar 2026 fee restructure — verify current subclass 485 charge",
      }),
      fee("dependent_adult", "Additional applicant 18+", {
        amount: 1150,
        currency: "AUD",
        unit: "per dependent adult",
      }),
      fee("dependent_child", "Additional applicant under 18", {
        amount: 575,
        currency: "AUD",
        unit: "per dependent child",
      }),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("biometrics", "Biometrics (government)", "No separate DHA fee"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "AUD",
        unit: "per applicant",
        notes: VFS_AU,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000046",
    "Australia – Work & Holiday Visa (Subclass 417/462)",
    "AUD",
    HOME_AFFAIRS,
    "Jul 2025",
    [
      fee("visa_application", "Working Holiday visa application charge", {
        amount: 635,
        currency: "AUD",
        unit: "per applicant",
        notes: "Subclass 417/462 · verify on immi.homeaffairs.gov.au",
      }),
      na("dependent_adult", "Dependants", "Not permitted on WHV"),
      na("dependent_child", "Child fee", "Not applicable"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("biometrics", "Biometrics (government)", "No separate DHA fee"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "AUD",
        unit: "per applicant",
        notes: VFS_AU,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not available"),
    ],
  ),
];
