import { breakdown, fee, na } from "./builders";
import type { GovtFeeBreakdownSource } from "./types";

const IRCC = "https://www.ircc.canada.ca/english/information/fees/fees.asp";
const VFS_IN = "Varies by VAC (India: check vfsglobal.com/ca) — courier, SMS, lounge optional";

export const CANADA_FEE_BREAKDOWNS: GovtFeeBreakdownSource[] = [
  breakdown(
    "b2000001-0001-4000-8000-000000000013",
    "Canada – Express Entry (Permanent Residence)",
    "CAD",
    IRCC,
    "Apr 2026",
    [
      fee("visa_application", "PR application processing fee (principal applicant)", {
        amount: 990,
        currency: "CAD",
        unit: "per applicant",
        notes: "Federal high-skilled / Express Entry · effective 30 Apr 2026",
      }),
      fee("dependent_adult", "Spouse / partner processing fee", {
        amount: 990,
        currency: "CAD",
        unit: "per dependent adult",
      }),
      fee("dependent_child", "Dependent child processing fee (under 22)", {
        amount: 270,
        currency: "CAD",
        unit: "per dependent child",
      }),
      fee("landing_rprf", "Right of Permanent Residence Fee (RPRF)", {
        amount: 600,
        currency: "CAD",
        unit: "per applicant",
        notes: "Principal applicant & spouse/partner · payable on approval (can defer) · children exempt",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
        notes: "CAD $170 for family of 2+ · $255 for groups of 3+",
      }),
      na("vfs_service", "VFS service charge", "Not applicable — IRCC online application"),
      na("health_surcharge", "Healthcare surcharge", "Not applicable — provincial healthcare after landing"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not available for PR applications"),
    ],
  ),
  breakdown(
    "c35e6051-f40f-47bf-9cac-0a386c47a336",
    "Canada – Student Visa (Study Permit)",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "Study permit application fee", {
        amount: 150,
        currency: "CAD",
        unit: "per applicant",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
        notes: "CAD $170 for family of 2+",
      }),
      na("dependent_adult", "Spouse OWP / visitor", "Separate application if spouse accompanies"),
      fee("dependent_child", "Minor child study permit / visitor record", {
        amount: 150,
        currency: "CAD",
        unit: "per dependent child",
        notes: "If study permit required for minor DLI student",
      }),
      na("landing_rprf", "Landing fee", "Not applicable for temporary resident permit"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "CAD",
        unit: "per applicant",
        notes: VFS_IN,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard for study permits"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000011",
    "Canada – Visitor Visa (TRV)",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "Visitor visa (TRV) application fee", {
        amount: 100,
        currency: "CAD",
        unit: "per applicant",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
      }),
      na("dependent_adult", "Family TRV", "Each family member pays separate TRV + biometrics"),
      na("dependent_child", "Child TRV", "Same fee as adult per person"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "CAD",
        unit: "per applicant",
        notes: VFS_IN,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard for TRV"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000016",
    "Canada – Super Visa",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "Super visa application fee", {
        amount: 100,
        currency: "CAD",
        unit: "per applicant",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
      }),
      na("dependent_adult", "Dependants on super visa", "Each applicant pays separately"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "CAD",
        unit: "per applicant",
        notes: VFS_IN,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable — private medical insurance required"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000012",
    "Canada – Spouse / Partner Sponsorship (PR)",
    "CAD",
    IRCC,
    "Apr 2026",
    [
      fee("visa_application", "Sponsorship + PR application (principal)", {
        amount: 570,
        currency: "CAD",
        unit: "per applicant",
        notes: "Family class sponsorship · effective 30 Apr 2026",
      }),
      fee("dependent_adult", "Sponsored spouse / partner", {
        amount: 570,
        currency: "CAD",
        unit: "per dependent adult",
      }),
      fee("dependent_child", "Dependent child", {
        amount: 180,
        currency: "CAD",
        unit: "per dependent child",
      }),
      fee("landing_rprf", "Right of Permanent Residence Fee (RPRF)", {
        amount: 600,
        currency: "CAD",
        unit: "per applicant",
        notes: "Spouse/partner pays · sponsored children exempt from RPRF",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
      }),
      na("vfs_service", "VFS service charge", "Online application — no VFS for in-Canada"),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not available"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000014",
    "Canada – Post-Graduation Work Permit (PGWP)",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "PGWP application fee", {
        amount: 255,
        currency: "CAD",
        unit: "per applicant",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
        notes: "If biometrics not already on file",
      }),
      na("dependent_adult", "Spouse OWP", "Separate open work permit application"),
      na("dependent_child", "Child visitor record", "Separate if required"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("vfs_service", "VFS service charge", "In-Canada online application"),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000015",
    "Canada – Work Permit",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "Work permit application fee", {
        amount: 255,
        currency: "CAD",
        unit: "per applicant",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
      }),
      na("dependent_adult", "Spouse OWP", "Separate application"),
      na("dependent_child", "Child visitor record", "Separate if required"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "CAD",
        unit: "per applicant",
        notes: VFS_IN,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000017",
    "Canada – Bridging Open Work Permit (BOWP)",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "BOWP application fee", {
        amount: 255,
        currency: "CAD",
        unit: "per applicant",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
        notes: "If not already valid on file",
      }),
      na("dependent_adult", "Dependants", "Separate applications"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("vfs_service", "VFS service charge", "In-Canada online"),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000018",
    "Canada – Study Permit Extension",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "Study permit extension fee", {
        amount: 150,
        currency: "CAD",
        unit: "per applicant",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
        notes: "If biometrics expired or not on file",
      }),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("vfs_service", "VFS service charge", "In-Canada online"),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000019",
    "Canada – Visitor Record",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "Visitor record application fee", {
        amount: 100,
        currency: "CAD",
        unit: "per applicant",
      }),
      na("biometrics", "Biometrics", "Usually already on file from initial entry"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("vfs_service", "VFS service charge", "In-Canada online"),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-00000000001b",
    "Canada – Spouse Dependent Open Work Permit",
    "CAD",
    IRCC,
    "Jun 2026",
    [
      fee("visa_application", "Open work permit application fee", {
        amount: 255,
        currency: "CAD",
        unit: "per applicant",
      }),
      fee("biometrics", "Biometrics fee", {
        amount: 85,
        currency: "CAD",
        unit: "per applicant",
      }),
      na("landing_rprf", "Landing fee", "Not applicable"),
      fee("vfs_service", "VAC / VFS service charge", {
        amount: null,
        currency: "CAD",
        unit: "per applicant",
        notes: VFS_IN,
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-00000000001a",
    "Canada – CAIPS / GCMS Notes",
    "CAD",
    "https://www.ircc.canada.ca/english/information/fees/fees.asp",
    "Jun 2026",
    [
      fee("visa_application", "Access to Information / GCMS request fee", {
        amount: 5,
        currency: "CAD",
        unit: "per application",
        notes: "ATIP / GCMS notes request — not a visa application",
      }),
      na("biometrics", "Biometrics", "Not applicable"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("vfs_service", "VFS service charge", "Not applicable"),
      na("dependent_adult", "Dependant fee", "Not applicable"),
      na("dependent_child", "Child fee", "Not applicable"),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not applicable"),
    ],
  ),
];
