import { breakdown, fee, na } from "./builders";
import type { GovtFeeBreakdownSource } from "./types";

const INZ = "https://www.immigration.govt.nz/new-zealand-visas/apply-for-a-visa/about-visa/fees";

export const NZ_FEE_BREAKDOWNS: GovtFeeBreakdownSource[] = [
  breakdown(
    "b2000001-0001-4000-8000-000000000061",
    "New Zealand – Student Visa",
    "NZD",
    INZ,
    "Jun 2026",
    [
      fee("visa_application", "Student visa application fee", {
        amount: 485,
        currency: "NZD",
        unit: "per applicant",
        notes: "Online application · verify on INZ fee table",
      }),
      fee("dependent_adult", "Partner / dependant visa", {
        amount: 485,
        currency: "NZD",
        unit: "per dependent adult",
        notes: "If included as secondary applicant",
      }),
      fee("dependent_child", "Dependent child", {
        amount: 485,
        currency: "NZD",
        unit: "per dependent child",
      }),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("biometrics", "Biometrics (government)", "No separate INZ biometrics fee"),
      fee("vfs_service", "VAC service charge", {
        amount: null,
        currency: "NZD",
        unit: "per applicant",
        notes: "Varies by VAC where biometrics collected",
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable — student insurance required"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000062",
    "New Zealand – Visitor Visa",
    "NZD",
    INZ,
    "Jun 2026",
    [
      fee("visa_application", "Visitor visa application fee", {
        amount: 341,
        currency: "NZD",
        unit: "per applicant",
        notes: "Online general visitor",
      }),
      na("dependent_adult", "Family visitor", "Each applicant pays separately"),
      na("dependent_child", "Child visitor", "Same fee per person"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("biometrics", "Biometrics (government)", "No separate INZ fee"),
      fee("vfs_service", "VAC service charge", {
        amount: null,
        currency: "NZD",
        unit: "per applicant",
        notes: "Varies by location",
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000063",
    "New Zealand – Partnership Visa",
    "NZD",
    INZ,
    "Jun 2026",
    [
      fee("visa_application", "Partnership-based residence visa fee", {
        amount: 1670,
        currency: "NZD",
        unit: "per applicant",
        notes: "Partnership / spouse category — verify exact visa type on INZ",
      }),
      fee("dependent_child", "Dependent child", {
        amount: 1670,
        currency: "NZD",
        unit: "per dependent child",
        notes: "If included in same application",
      }),
      na("landing_rprf", "Landing fee", "Included in residence application"),
      na("biometrics", "Biometrics (government)", "No separate INZ fee"),
      fee("vfs_service", "VAC service charge", {
        amount: null,
        currency: "NZD",
        unit: "per applicant",
        notes: "Varies by location",
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000064",
    "New Zealand – Skilled Migrant Category (SMC)",
    "NZD",
    INZ,
    "Jun 2026",
    [
      fee("visa_application", "SMC Expression of Interest (EOI)", {
        amount: 680,
        currency: "NZD",
        unit: "per applicant",
        notes: "EOI submission fee",
      }),
      fee("other", "SMC residence application fee", {
        amount: 4890,
        currency: "NZD",
        unit: "per applicant",
        notes: "After ITA — residence application",
      }),
      fee("dependent_adult", "Partner (SMC)", {
        amount: 4890,
        currency: "NZD",
        unit: "per dependent adult",
        notes: "Same residence fee tier",
      }),
      fee("dependent_child", "Dependent child (SMC)", {
        amount: 4890,
        currency: "NZD",
        unit: "per dependent child",
      }),
      na("landing_rprf", "Landing fee", "Included in residence fee"),
      na("biometrics", "Biometrics (government)", "No separate INZ fee"),
      fee("vfs_service", "VAC service charge", {
        amount: null,
        currency: "NZD",
        unit: "per applicant",
        notes: "Varies by location",
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not available"),
    ],
  ),
  breakdown(
    "b2000001-0001-4000-8000-000000000065",
    "New Zealand – Post Study Work Visa",
    "NZD",
    INZ,
    "Jun 2026",
    [
      fee("visa_application", "Post-study work visa fee", {
        amount: 700,
        currency: "NZD",
        unit: "per applicant",
        notes: "Verify current PSWV fee on INZ",
      }),
      na("dependent_adult", "Partner OWP", "Separate partnership-based work visa if applicable"),
      na("dependent_child", "Child visitor/student", "Separate application"),
      na("landing_rprf", "Landing fee", "Not applicable"),
      na("biometrics", "Biometrics (government)", "No separate INZ fee"),
      fee("vfs_service", "VAC service charge", {
        amount: null,
        currency: "NZD",
        unit: "per applicant",
        notes: "Varies by location",
      }),
      na("health_surcharge", "Healthcare surcharge", "Not applicable"),
      na("sevis", "SEVIS fee", "US only"),
      na("priority_service", "Priority processing", "Not standard"),
    ],
  ),
];
