const q = (level, question, correct, explanation, distractors) => ({
  level,
  question,
  options: [correct, ...distractors],
  correctIndex: 0,
  explanation,
});

const makeLevel = (level, rows, distractors) =>
  rows.map(([question, correct, explanation]) =>
    q(level, question, correct, explanation, distractors),
  );

const distractors = {
  pgwp: ["A visitor visa issued for tourism only", "An employer-specific LMIA approval", "A permanent resident card"],
  "work-permit": ["A regular visitor record", "A provincial health card", "A permanent resident visa"],
  "express-entry": ["A temporary visitor visa category", "A school admissions system", "A passport renewal service"],
  "super-visa": ["A work permit for Canadian employers", "A permanent residence sponsorship approval", "An Express Entry invitation"],
  caips: ["A visa counterfoil", "A work permit exemption code", "A language test certificate"],
  "spouse-dependent-owp": ["A closed LMIA work permit only", "A visitor visa with no work rights", "A permanent resident card"],
};

const rows = {
  pgwp: {
    1: [
      ["What is the main purpose of a Post-Graduation Work Permit?", "To let eligible graduates work in Canada after completing studies", "A PGWP is an open work permit for eligible graduates of qualifying Canadian programs."],
      ["Which school factor is essential for PGWP eligibility?", "Completion of a PGWP-eligible program at a designated learning institution", "The school must be a DLI and the completed program must be eligible for PGWP purposes."],
      ["How many PGWPs can a person normally receive?", "One in a lifetime", "A PGWP is generally a one-time opportunity, so timing and program choice matter."],
      ["What type of work permit is a PGWP?", "An open work permit", "A PGWP usually allows work for most employers in Canada, subject to standard restrictions."],
      ["Which document commonly proves program completion for a PGWP?", "A completion letter or final transcript", "Applicants commonly use school-issued completion evidence to prove they finished the program."],
      ["What mainly determines the possible length of a PGWP?", "The length and eligibility of the completed study program", "PGWP validity is tied mainly to eligible program length, subject to policy limits."],
      ["What does DLI mean in PGWP planning?", "Designated Learning Institution", "A DLI is approved to host international students, but not every DLI program supports a PGWP."],
      ["When does a student usually become eligible to apply for a PGWP?", "After receiving confirmation that the eligible program is complete", "The application is tied to program completion, not simply attending classes."],
      ["Is a job offer normally required for a PGWP application?", "No, a PGWP usually does not require a job offer", "Because it is open, the PGWP is not normally based on a specific employer offer."],
      ["What is the usual maximum PGWP duration under standard rules?", "Up to three years", "The standard maximum is generally up to three years, depending on eligibility and program length."],
      ["Which applicant is most clearly connected to PGWP eligibility?", "A graduate of an eligible Canadian post-secondary program", "PGWP eligibility starts with completing a qualifying Canadian study program."],
      ["Why should students verify PGWP eligibility before enrolling?", "Some DLI programs do not lead to a PGWP", "A school can be a DLI while a specific program is still not PGWP eligible."],
      ["What future immigration advantage can PGWP work experience create?", "It can help build Canadian skilled work experience", "Canadian work experience can support future pathways such as Canadian Experience Class."],
      ["What status does a PGWP holder have in Canada?", "Temporary resident worker status", "A PGWP does not itself make the holder a permanent resident."],
      ["Which program length is often too short for standard PGWP eligibility?", "A program shorter than eight months", "Programs below the minimum duration generally do not support PGWP issuance."],
      ["Who issues a PGWP?", "Immigration, Refugees and Citizenship Canada", "IRCC assesses and issues work permits, including PGWPs."],
      ["What does PGWP stand for?", "Post-Graduation Work Permit", "PGWP is the common abbreviation for Post-Graduation Work Permit."],
      ["Which condition is least typical for a PGWP?", "Being tied to one named employer", "A PGWP is open and usually not employer-specific."],
      ["Why is the one-time nature of a PGWP important?", "A poor timing choice can affect future work and PR planning", "Since a PGWP is generally issued once, applicants should plan the timing carefully."],
      ["Which school outcome matters most for a PGWP application?", "Successful completion of the eligible credential", "The application depends on proof that the applicant completed the eligible program."],
      ["What does an open work permit generally allow?", "Work for most employers without a separate LMIA", "Open work permits are not tied to a specific employer, though conditions still apply."],
      ["What should a student check on the official DLI list?", "Whether the institution and program support PGWP eligibility", "Official eligibility details help avoid enrolling in a non-qualifying program."],
      ["Which previous status is usually relevant before a PGWP?", "Study permit status", "Most applicants first studied in Canada with valid study authorization."],
      ["What is a common risk of waiting too long after completion?", "Missing the PGWP application deadline", "PGWP applications are deadline-sensitive after completion documents become available."],
      ["What does a PGWP not guarantee by itself?", "Permanent residence", "The PGWP can support future plans, but PR requires a separate application and approval."],
    ],
    2: [
      ["Which two documents are commonly uploaded for PGWP completion proof?", "Completion letter and final transcript", "These documents help prove successful completion of an eligible program."],
      ["Why is full-time study history important in many PGWP cases?", "It is a core eligibility expectation with limited exceptions", "IRCC commonly reviews whether the student maintained required study status."],
      ["Which term may be part-time without necessarily harming PGWP eligibility?", "The final academic session needed to complete the program", "A final-term exception can apply when a reduced load is all that remains."],
      ["Why does passport validity matter for PGWP issuance?", "IRCC cannot issue a permit beyond passport validity", "A short passport can cause a shortened PGWP even when the person is eligible for more time."],
      ["What should a student do if the passport expires soon?", "Consider renewing before applying if timing allows", "A longer-valid passport can prevent avoidable shortening of the permit."],
      ["What is maintained status in the PGWP process?", "Status that may continue after a timely application is filed", "Maintained status depends on filing before expiry and meeting the relevant conditions."],
      ["Why should work after completion be checked carefully?", "Work authorization changes after completion and before PGWP approval", "Graduates must satisfy specific conditions to work while the PGWP application is pending."],
      ["Which evidence can support a scheduled break in studies?", "An academic calendar or school letter confirming the break", "Official school evidence can show the break was scheduled and acceptable."],
      ["What can happen if completion evidence is incomplete?", "IRCC may request more information or refuse if eligibility is not proven", "The applicant must prove that all PGWP requirements are met."],
      ["Why should identity details match across PGWP documents?", "Consistency reduces avoidable concerns about the applicant's record", "Names and dates of birth should align or be explained with evidence."],
      ["What fees are commonly associated with a PGWP application?", "Work permit processing and open work permit holder fees", "PGWP applicants generally pay both required work permit fees."],
      ["What should a student document after changing schools?", "The transfer, study history, and final program eligibility", "Transfers can affect records, timelines, and eligibility analysis."],
      ["How can two eligible one-year programs affect PGWP length?", "They may be combined for a longer PGWP if policy conditions are met", "Some completed programs can be combined under timing and eligibility rules."],
      ["Why keep copies of all study permits and transcripts?", "They can prove study history and compliance", "Historical records help explain the applicant's timeline."],
      ["What travel issue should PGWP applicants consider during processing?", "Whether they have a valid TRV or eTA for re-entry", "A work permit application does not replace travel document requirements."],
      ["What is the role of biometrics in some PGWP applications?", "Applicants may need valid biometrics or may be asked to provide them", "Biometrics are an identity and security requirement for many applicants."],
      ["How should a school name change be handled?", "Provide documents linking the old and new institution records", "Clear documentation helps IRCC understand institutional changes."],
      ["Which evidence can support an authorized medical leave?", "School-approved leave records and relevant medical documents", "Authorized leaves should be supported with official evidence."],
      ["Why is the completion-confirmation date important?", "It can start the PGWP application deadline", "Applicants should track when written completion confirmation first became available."],
      ["What is the best response to an additional document request?", "Respond by the deadline with targeted evidence", "Timely and relevant responses address the officer's specific concern."],
      ["What should be reviewed before applying from inside Canada?", "Current status and work authorization after completion", "Applicants need to know whether they may remain and work while awaiting a decision."],
      ["Which issue can complicate a PGWP application?", "Unauthorized breaks or unexplained part-time terms", "Study gaps can raise eligibility questions and should be documented."],
      ["What should an applicant include for a non-standard study timeline?", "A clear chronology with official supporting documents", "Chronologies help officers understand transfers, breaks, and completion timing."],
      ["Why is an online account important after submission?", "IRCC sends requests and decisions through the portal", "Applicants must monitor the account to avoid missing deadlines."],
      ["What should be checked before relying on work while a PGWP is pending?", "That the applicant met the conditions for interim work authorization", "Not every graduate can work automatically; the conditions must be met."],
    ],
    3: [
      ["Why can distance learning history matter in a PGWP review?", "Rules have varied by period and may affect eligible study time", "Online study must be assessed under the policy that applied to the study period."],
      ["What is the risk of full-time work before written completion confirmation?", "The person may still be bound by student work limits", "Work authorization changes around completion and must be timed correctly."],
      ["Why must previous refusals be disclosed accurately?", "Omissions can create misrepresentation concerns", "Incorrect immigration-history answers can have consequences beyond a refusal."],
      ["When might a shortened PGWP be extendable?", "When it was shortened only because the passport expired", "A passport-limited PGWP may be extendable to the eligible length."],
      ["Why are unofficial school promises risky?", "Marketing claims do not override IRCC rules", "Eligibility depends on official criteria and officer assessment."],
      ["Why may a leave from studies need careful evidence?", "The officer must see it was authorized and within policy limits", "Authorized leave analysis is fact-specific and document-driven."],
      ["What can happen after completing a non-PGWP eligible private program?", "The program may not support PGWP eligibility", "Not every program at a Canadian institution qualifies for a PGWP."],
      ["How should inconsistent completion dates be handled?", "Explain and support the correct timeline", "Date inconsistencies can affect deadlines and eligibility."],
      ["Why can unauthorized work during studies affect PGWP eligibility?", "It may show non-compliance with study permit conditions", "Applicants must comply with temporary resident conditions."],
      ["Which case needs a stronger explanation letter?", "A gap caused by strike, medical leave, or program transfer", "Non-standard timelines should be explained with evidence."],
      ["What is the risk of filing after status expires?", "The applicant may need restoration and may lack work authorization", "Late filing can affect both legal status and work rights."],
      ["Why preserve proof of full-time enrollment each term?", "It can demonstrate continuous compliance", "Term records help show the applicant met study requirements."],
      ["How can a co-op permit support PGWP analysis?", "It can show required work placements were authorized", "Co-op authorization helps explain program-related work."],
      ["Why is mid-program part-time study risky?", "It can breach PGWP full-time study expectations unless an exception applies", "Part-time terms outside recognized exceptions can undermine eligibility."],
      ["Why is the final-term exception narrow?", "It applies when reduced course load is needed to finish the program", "It is not a general permission to study part-time anytime."],
      ["What does a refusal for program ineligibility mean?", "The officer was not satisfied the program met PGWP rules", "Program eligibility is a threshold issue."],
      ["Which record best supports a school-scheduled break?", "An official academic calendar or registrar letter", "Official records carry more weight than informal statements."],
      ["Why can travel after applying create practical issues?", "Re-entry depends on valid travel documents and border assessment", "Processing and travel authorization are separate concerns."],
      ["How should a potential non-compliance period be addressed?", "Disclose it accurately and provide factual context", "Transparency reduces misrepresentation risk and helps explain the record."],
      ["Why can a withdrawn semester matter after graduation?", "It may affect continuous study and authorized leave analysis", "Graduation alone may not cure every study-history issue."],
      ["Which issue most likely needs legal advice before PGWP submission?", "Prior unauthorized work combined with expired status", "Multiple compliance problems can affect eligibility and future applications."],
      ["What does officer discretion focus on in complex PGWP files?", "Whether evidence proves the requirements are met", "The decision is evidence-based and tied to legal and policy criteria."],
      ["Why should explanation letters be evidence-linked?", "They help the officer connect facts to documents", "Good explanations clarify the record without replacing proof."],
      ["What can follow from misrepresenting study history?", "Refusal and possible inadmissibility", "Misrepresentation can lead to serious immigration consequences."],
      ["What is the best strategy for a non-standard PGWP history?", "Build a complete documented chronology", "A clear chronology helps address eligibility concerns transparently."],
    ],
  },
  "work-permit": {
    1: [
      ["What is an employer-specific work permit?", "A permit tied to a named employer and job conditions", "Closed permits list employment conditions such as employer, role, location, and validity."],
      ["What does LMIA stand for?", "Labour Market Impact Assessment", "An LMIA is an ESDC assessment used in many TFWP cases."],
      ["Which program commonly requires an LMIA?", "Temporary Foreign Worker Program", "The TFWP is generally LMIA-based."],
      ["What is the purpose of an LMIA?", "To assess the labour market impact of hiring a foreign worker", "ESDC reviews whether hiring the worker will have a positive or neutral impact."],
      ["What does IMP stand for?", "International Mobility Program", "The IMP includes LMIA-exempt work permit categories."],
      ["What does LMIA-exempt mean?", "A work permit may be issued under a specific exemption code without an LMIA", "LMIA-exempt does not necessarily mean work-permit exempt."],
      ["Who usually applies for an LMIA?", "The Canadian employer", "Employers apply to ESDC/Service Canada before the worker applies for the permit."],
      ["What supports a worker's application after a positive LMIA?", "LMIA approval and employment offer details", "The worker uses the LMIA and offer documents to support the permit request."],
      ["What is an open work permit?", "A permit not tied to one specific employer", "Open permits allow work for most employers, subject to conditions."],
      ["What is a typical closed-permit condition?", "Work only for the employer named on the permit", "Working outside listed conditions can create compliance problems."],
      ["What does TFWP stand for?", "Temporary Foreign Worker Program", "TFWP refers to LMIA-based temporary foreign worker hiring."],
      ["Who issues most work permits?", "Immigration, Refugees and Citizenship Canada", "IRCC issues work permits while ESDC assesses LMIAs."],
      ["Who assesses most LMIA applications?", "Employment and Social Development Canada or Service Canada", "ESDC/Service Canada reviews labour market factors."],
      ["Which category can be LMIA-exempt?", "Some intra-company transferees", "Certain ICT cases may qualify under IMP rules if criteria are met."],
      ["What is a job offer's role?", "It describes the proposed employment position and conditions", "Work permit applications often rely on detailed employment terms."],
      ["What is the employer compliance fee linked to?", "Many LMIA-exempt employer-specific IMP offers", "Employers often submit the offer and pay a fee through the Employer Portal."],
      ["Which portal is used for many LMIA-exempt offers?", "Employer Portal", "The Employer Portal links the offer to the worker's application."],
      ["What does a foreign worker usually need before starting work?", "Authorization to work", "Foreign nationals generally need work authorization unless an exemption applies."],
      ["What is not a work permit by itself?", "A job offer letter", "A job offer supports an application but is not authorization to work."],
      ["What is a NOC code used for?", "Classifying job duties and skill profile", "NOC codes help classify occupations for immigration and labour programs."],
      ["Which pathway is most tied to recruitment evidence?", "LMIA-based TFWP", "Many LMIA streams require recruitment and labour market evidence."],
      ["What does a positive LMIA generally indicate?", "Hiring is expected to have a positive or neutral labour market impact", "A positive LMIA can support an employer-specific work permit."],
      ["What does a negative LMIA usually mean?", "It cannot support the requested work permit", "A negative LMIA does not provide the needed labour market support."],
      ["Which worker is likely on a closed permit?", "A cook authorized for one named restaurant", "Employer-specific permits are tied to the listed employer and role."],
      ["Why read printed permit conditions?", "They define what work is authorized", "Working outside permit conditions can affect current and future status."],
    ],
    2: [
      ["What is usually first in an LMIA-based hiring process?", "The employer identifies the correct LMIA stream and recruitment requirements", "The employer must satisfy stream-specific requirements before the worker applies."],
      ["Why are recruitment records important for LMIAs?", "They show efforts to hire Canadians or permanent residents first", "Recruitment evidence is central to many labour market assessments."],
      ["Which wage issue is commonly assessed in LMIAs?", "Whether the offered wage meets prevailing wage rules", "ESDC reviews wages for the occupation and location."],
      ["What does an employer submit for many IMP closed permits?", "An offer of employment through the Employer Portal", "Many LMIA-exempt employer-specific permits require an online employer submission."],
      ["Which number may the worker need from the Employer Portal?", "Offer of employment number", "This number links the employer submission to the worker's application."],
      ["What should be consistent across offer and application?", "Title, duties, wage, employer, and location", "Consistency helps officers assess the employment and category."],
      ["Why must the NOC match actual duties?", "Officers assess duties, not job title alone", "A title cannot overcome duties that do not fit the claimed NOC."],
      ["What is a transition plan?", "An employer plan to reduce reliance on foreign workers", "Some high-wage LMIA cases require transition planning."],
      ["What can trigger low-wage LMIA rules?", "Offered wage below the provincial or territorial median", "LMIA streams often distinguish high-wage and low-wage roles by median wage."],
      ["What is a low-wage cap?", "A limit on the proportion of low-wage temporary foreign workers", "Low-wage rules can cap TFWs at a worksite."],
      ["Why might a medical exam be required?", "Occupation, residence history, or public health rules can trigger it", "Medical requirements depend on job type and personal history."],
      ["When should a closed-permit holder apply to change employers?", "Before starting work for the new employer", "Closed permits are not automatically transferable."],
      ["What is a port of entry letter of introduction?", "A letter supporting permit issuance at entry, not the permit itself", "The actual permit is issued separately when requirements are met."],
      ["Who may need a TRV or eTA besides work permit approval?", "Workers who require a travel document to board and enter Canada", "Travel authorization and work authorization are related but separate."],
      ["What should an employer avoid in LMIA recruitment?", "Unfairly tailoring requirements to exclude qualified Canadians", "Artificially restrictive recruitment can undermine the labour market test."],
      ["What is a compliance inspection?", "A review of whether the employer met program obligations", "Employers can be inspected for wages, duties, conditions, and records."],
      ["Which proof can show the worker is qualified?", "Resume, credentials, licences, and reference letters", "The worker must often show they can perform the job."],
      ["Why check regulated occupations?", "Provincial licensing may be required", "Some jobs require registration before the worker can legally perform them."],
      ["What is biometrics' role in work permits?", "Identity and security screening", "Many applicants must provide fingerprints and a photo unless exempt."],
      ["Which job change should be addressed before work continues?", "A substantial change in employer, duties, wage, or location", "Material changes can make the current permit inaccurate."],
      ["What is maintained status for a work permit extension?", "Temporary status that may continue after a timely extension application", "Maintained status usually preserves prior conditions while a decision is pending."],
      ["What is needed to move from one closed employer to another?", "A new work permit supported by the new employer's authorization basis", "Changing closed employers normally requires a new authorization."],
      ["What should an LMIA-exempt explanation identify?", "The exemption code and evidence meeting its criteria", "LMIA-exempt categories require specific legal criteria."],
      ["Why does the employment contract matter?", "It confirms duties, wage, hours, benefits, and location", "Contracts help prove offer terms and employer obligations."],
      ["What is the usual sequence for TFWP work permits?", "Employer obtains LMIA, then worker applies for the permit", "A positive LMIA is usually needed before the worker's application."],
    ],
    3: [
      ["What is the risk of working for a different employer on a closed permit?", "Unauthorized work and future admissibility concerns", "Closed permits authorize only the listed employment."],
      ["Why can employer compliance history affect future hiring?", "Non-compliant employers may face bans, penalties, or refusal risk", "Program compliance findings can affect future foreign-worker hiring."],
      ["What is the issue with paying less than the approved wage?", "It may breach employer obligations and permit conditions", "Employers must generally provide the approved wages and conditions."],
      ["When is a duty change problematic?", "When duties no longer match the approved NOC or offer", "Material duty changes can require a new assessment."],
      ["Why is NOC misclassification risky?", "It can undermine LMIA, work permit, and later PR claims", "NOC affects eligibility, wages, duties, and immigration alignment."],
      ["What is a risk in owner-operator style LMIA cases?", "Questions about genuineness, control, and labour market need", "Ownership-linked employment requires careful evidence."],
      ["What weakens an LMIA recruitment file?", "Rejecting qualified Canadians without documented job-related reasons", "Recruitment decisions should be legitimate and documented."],
      ["Why are layoffs near an LMIA application sensitive?", "They may raise concerns about labour need and impact on Canadians", "Recent layoffs can affect whether hiring a foreign worker is justified."],
      ["What is the significance of LMIA expiry?", "The worker must use it for a permit application within validity", "An LMIA has a validity period for supporting an application."],
      ["Which issue can trigger inadmissibility concerns?", "False documents or undisclosed immigration history", "Misrepresentation can have serious consequences."],
      ["Why distinguish business visitor from worker?", "Some activities require a work permit while limited business activities may not", "Misclassifying work as business visits can create unauthorized work."],
      ["What is advanced in intra-company transferee cases?", "Proving corporate relationship and specialized knowledge or executive capacity", "ICT cases require evidence about both companies and the worker's role."],
      ["Why can start-up employers face scrutiny?", "They must prove they can genuinely employ and pay the worker", "New businesses may need stronger operational and financial evidence."],
      ["What is risky about generic NOC job descriptions?", "They may fail to prove the actual job is genuine", "Applications should describe real duties, not copied text alone."],
      ["What is central in significant benefit IMP cases?", "Evidence of important social, cultural, or economic benefit", "Significant benefit exemptions require persuasive Canada-benefit evidence."],
      ["Why can unauthorized work harm later Express Entry plans?", "It may not count and can raise compliance issues", "Unauthorized experience can affect both eligibility and credibility."],
      ["How should a procedural fairness letter be handled?", "Address the concerns with evidence before the deadline", "A PFL is a chance to respond before possible refusal."],
      ["Why keep employer records after the worker starts?", "They may be needed during compliance inspections", "Employer obligations continue after permit issuance."],
      ["Which change may require a fresh LMIA or offer submission?", "A material change to employer, duties, wage, or location", "Material changes can require new authorization."],
      ["Why do provincial employment standards matter?", "Employer obligations include applicable workplace laws", "Foreign-worker programs do not override workplace standards."],
      ["What is a risk of inflated recruitment requirements?", "They may appear designed to exclude local applicants", "Requirements should be reasonable and necessary."],
      ["Why avoid starting before the permit is issued or activated?", "Approval steps may not yet equal legal authorization to work", "Work can begin only when the worker has proper authorization."],
      ["What supports a reciprocal employment exemption?", "Evidence of balanced opportunities for Canadians abroad", "Reciprocity relies on mutual benefit."],
      ["What can complicate a work permit extension?", "Expired passport, changed duties, or employer non-compliance", "Extensions depend on both worker and employer circumstances."],
      ["What is safest when work conditions no longer match the permit?", "Obtain proper authorization before continuing changed work", "Correct authorization reduces compliance risk."],
    ],
  },
  "express-entry": {
    1: [
      ["What is Express Entry?", "An online system for managing certain economic PR applications", "Express Entry manages profiles and applications for major federal economic programs."],
      ["Which federal programs are managed through Express Entry?", "FSW, CEC, and FST", "Express Entry includes Federal Skilled Worker, Canadian Experience Class, and Federal Skilled Trades."],
      ["What does CRS stand for?", "Comprehensive Ranking System", "CRS is the points system used to rank candidates."],
      ["What is an ITA?", "Invitation to Apply", "An ITA invites a candidate to submit a complete PR application."],
      ["What does FSW stand for?", "Federal Skilled Worker", "FSW is a federal economic program managed through Express Entry."],
      ["What does CEC stand for?", "Canadian Experience Class", "CEC is for candidates with qualifying Canadian skilled work experience."],
      ["What does FST stand for?", "Federal Skilled Trades", "FST is the federal skilled trades program."],
      ["What can a provincial nomination do in Express Entry?", "Add significant CRS points", "An enhanced nomination can add major CRS points and often leads to an ITA."],
      ["What is the Express Entry pool?", "Eligible candidate profiles waiting for draws", "Profiles in the pool are ranked against other candidates."],
      ["Which factors commonly affect CRS?", "Age, education, language, and work experience", "Core CRS factors include human capital and skill transferability criteria."],
      ["What is a language test used for?", "Proving English or French proficiency", "Approved language results affect eligibility and CRS."],
      ["What is an ECA used for?", "Comparing foreign education to Canadian standards", "An ECA can be required for foreign education points and FSW eligibility."],
      ["What must exist before entering the pool?", "Eligibility for at least one Express Entry program", "A candidate must meet a managed program's criteria."],
      ["Who uses Express Entry?", "Skilled economic immigration candidates", "Express Entry is focused on skilled economic permanent residence."],
      ["What happens after an ITA?", "The candidate submits a complete electronic PR application by the deadline", "An ITA starts the deadline for the full application and evidence."],
      ["What is an Express Entry draw?", "An invitation round where IRCC invites selected candidates", "IRCC conducts rounds based on CRS, program, category, or other criteria."],
      ["What is proof of funds used for?", "Showing settlement funds where required", "Some applicants must show available funds to settle in Canada."],
      ["Which program is tied to Canadian skilled work experience?", "Canadian Experience Class", "CEC is designed for qualifying Canadian work experience."],
      ["What is a primary occupation?", "The occupation used to assess qualifying skilled work experience", "The primary occupation structures work history and eligibility."],
      ["What is a CRS cut-off score?", "The minimum score invited in a particular draw", "Each draw has its own cut-off and invitation criteria."],
      ["What are police certificates used for?", "Criminality screening", "Police certificates support admissibility assessment."],
      ["What are immigration medical exams used for?", "Health admissibility assessment", "IRCC uses medical exams to assess health admissibility."],
      ["What is an enhanced PNP stream?", "A provincial stream aligned with Express Entry", "Enhanced nominations connect with Express Entry and can add CRS points."],
      ["What does entering the pool not create by itself?", "Permanent resident status", "Entering the pool is not the same as being invited or approved."],
      ["Why keep an Express Entry profile accurate?", "Unsupported information can cause refusal or misrepresentation concerns", "The PR application must support the profile's claims."],
    ],
    2: [
      ["Which document is needed for foreign education CRS points?", "Educational Credential Assessment", "An ECA is commonly required for points for foreign education."],
      ["What should an employment reference letter include?", "Duties, title, dates, hours, salary, and employer details", "Detailed letters help prove skilled work and NOC alignment."],
      ["Why are duties more important than title alone?", "NOC matching is based mainly on duties", "Officers compare actual duties to the claimed NOC."],
      ["What if circumstances change after ITA?", "The application must remain accurate and eligibility must still be met", "Post-ITA changes can affect CRS, eligibility, and documents."],
      ["What deadline follows an ITA?", "A fixed deadline to submit the electronic PR application", "The account shows the submission deadline."],
      ["What should proof of funds letters show?", "Available, transferable, unencumbered settlement money", "Funds must satisfy IRCC settlement-fund requirements."],
      ["Who may not need settlement funds?", "A CEC applicant or applicant with qualifying arranged employment where rules allow", "Proof-of-funds exemptions depend on program and employment context."],
      ["What is arranged employment for CRS?", "A qualifying valid job offer meeting Express Entry rules", "Not every job offer qualifies for CRS points."],
      ["Why might an LMIA matter for job offer points?", "Some offers need LMIA support unless an exemption applies", "Valid job offer rules can require LMIA or qualifying LMIA-exempt status."],
      ["How is Canadian work counted for CEC?", "Authorized paid skilled work in Canada", "CEC requires qualifying Canadian skilled work gained with authorization."],
      ["Which work is excluded from CEC experience?", "Unauthorized work", "Unauthorized work cannot be used as qualifying Canadian experience."],
      ["How can part-time work count?", "As equivalent experience if it meets program rules", "Part-time hours can count when properly calculated."],
      ["Why calculate dates precisely?", "Claiming experience too early can cause refusal", "Eligibility often depends on exact dates, months, and hours."],
      ["How can a spouse's language test affect CRS?", "It may add points for an accompanying spouse", "Spousal factors can change CRS."],
      ["What should be done if a score is inflated before accepting ITA?", "Correct or decline if points cannot be supported", "Unsupported CRS claims can cause refusal."],
      ["What proves identity and travel history basics?", "Passport pages", "Passports support identity, status history, and travel history."],
      ["Why do police certificate country rules matter?", "Requirements depend on where and how long the applicant lived", "Applicants must follow country-specific instructions."],
      ["What is personal history used for?", "Accounting for activities without unexplained gaps", "Personal history supports background and consistency review."],
      ["What is a medical instruction process?", "A way to complete the required immigration medical exam", "Medical exams are part of PR admissibility screening."],
      ["Which fees are common at PR submission?", "Processing fee and right of permanent residence fee", "Express Entry PR applications include government fees."],
      ["Why prepare translations properly?", "Non-English or non-French documents need acceptable translations", "Translations must meet IRCC document standards."],
      ["What is a letter of explanation best for?", "Clarifying specific document issues or unusual facts", "It should clarify evidence, not replace eligibility."],
      ["What should be checked after new language results?", "Whether CRS and program eligibility changed", "Language results can affect thresholds and ranking."],
      ["Why do PNP nomination conditions matter?", "The applicant may need to maintain intent and truthful provincial information", "Federal review continues after nomination."],
      ["How should non-accompanying family be handled?", "Disclose them and complete required examinations unless exempted", "Family members must be disclosed even if they are not immigrating."],
    ],
    3: [
      ["What if CRS drops below the draw cut-off after ITA?", "The application may be refused if invitation criteria are no longer met", "Applicants must support the score that justified the invitation."],
      ["Why is the lock-in date important?", "Some facts are assessed at receipt while others must remain true", "Timing affects age, documents, eligibility, and admissibility analysis."],
      ["What is a common work-experience misrepresentation risk?", "Inflating duties, dates, hours, or salary", "Unsupported work claims can lead to refusal and inadmissibility."],
      ["Why is self-employment complicated?", "Counting rules and evidence standards differ by program", "Self-employment may count differently for foreign experience and CEC."],
      ["What is the risk of choosing a NOC by title only?", "Duties may not substantially match the claimed NOC", "NOC alignment depends on actual duties."],
      ["What can make a job offer invalid for CRS points?", "Failure to meet duration, employer, LMIA, exemption, or occupation rules", "A valid CRS job offer has specific requirements."],
      ["Why disclose all prior refusals?", "Failure to disclose can be misrepresentation", "Immigration history must be truthful and complete."],
      ["What is the risk of personal-history gaps?", "They can trigger background questions or document requests", "Complete timelines support consistency and admissibility review."],
      ["How can proof of funds become non-compliant?", "Funds are borrowed, encumbered, unavailable, or too low", "Settlement funds must be genuinely available."],
      ["Why can a PNP nominee still be refused federally?", "Federal officers still assess admissibility, eligibility, and truthfulness", "Nomination does not eliminate federal review."],
      ["What if language results expire before eAPR submission?", "They cannot support the application if no longer valid", "Language tests must be valid when required."],
      ["Why is a coworker-only reference letter risky?", "It may carry less weight than employer-issued evidence", "Alternative evidence needs strong explanation and corroboration."],
      ["Why plan police certificates early?", "Some countries take longer or have specific validity rules", "Country-specific instructions can affect timing."],
      ["When might a procedural fairness response be needed?", "When an officer doubts authenticity or work experience", "A PFL allows response to serious concerns."],
      ["What is safest for a borderline NOC claim?", "Choose the NOC best supported by duties and evidence", "The strongest NOC is the one the records support."],
      ["Why track marital-status changes?", "They can affect CRS, forms, family admissibility, and documents", "Family composition changes must be disclosed."],
      ["What is a risk with Canadian work gained as a full-time student?", "Some student work may be excluded from CEC eligibility", "CEC has specific exclusions for student work."],
      ["Why do payroll records strengthen work evidence?", "They corroborate paid employment, hours, and dates", "Pay records support the genuineness and duration of employment."],
      ["What is the risk of missing the eAPR deadline?", "Late or missing documents may lead to rejection or refusal", "Express Entry deadlines are strict."],
      ["Why disclose non-accompanying dependants?", "Undisclosed family can create future sponsorship and admissibility problems", "All family members must be disclosed as required."],
      ["What if claimed CRS points cannot be proven?", "Refusal and possible misrepresentation finding", "The applicant must prove eligibility and claimed points."],
      ["Why do category-based draws require care?", "The candidate must meet the specific category criteria", "Category-based invitations rely on additional attributes."],
      ["What if arranged employment ends after ITA?", "Job offer points may no longer be valid", "Job offer points depend on continuing qualifying circumstances."],
      ["How should unobtainable documents be handled?", "Provide proof of attempts, explanation, and acceptable alternatives if allowed", "Diligent efforts should be documented."],
      ["Why can an old immigration violation affect Express Entry?", "It may raise admissibility or credibility concerns", "Past compliance can remain relevant."],
    ],
  },
  "super-visa": {
    1: [
      ["Who is the super visa primarily for?", "Parents and grandparents of Canadian citizens or permanent residents", "The super visa supports extended visits by eligible parents and grandparents."],
      ["What status does a super visa grant?", "Temporary resident visitor status", "It is not permanent residence or work authorization."],
      ["Who usually supports a super visa application in Canada?", "A child or grandchild who is a citizen or permanent resident", "The host must have the required relationship and status."],
      ["What does LICO mean?", "Low Income Cut-Off", "The host must meet minimum income requirements based on family size."],
      ["Which document is central to super visa eligibility?", "Private medical insurance meeting IRCC requirements", "Qualifying medical insurance is a core requirement."],
      ["How does a super visa differ from a regular visitor visa?", "It can allow longer stays per entry for eligible parents and grandparents", "The super visa is designed for extended family visits."],
      ["What does multi-entry mean?", "The holder may seek entry multiple times while the visa is valid", "Each entry is still assessed by border officers."],
      ["Who must meet the income requirement?", "The inviting child or grandchild's household as applicable", "The Canadian host must show sufficient income."],
      ["What proves the host's Canadian status?", "Canadian passport, citizenship certificate, or PR card", "The host must prove citizenship or permanent residence."],
      ["Which relationship must be documented?", "Parent or grandparent relationship to the Canadian host", "Civil documents often prove the family link."],
      ["Does a super visa allow work in Canada?", "No, separate work authorization is required", "Super visa holders are visitors."],
      ["What is an invitation letter used for?", "Explaining the visit, support, accommodation, and relationship", "The invitation organizes the host's support evidence."],
      ["Which applicant factor remains important?", "Temporary intent and home-country ties", "Applicants must satisfy temporary resident requirements."],
      ["What is the role of a medical exam?", "Health admissibility assessment", "Super visa applicants commonly face medical screening."],
      ["Does meeting LICO guarantee approval?", "No, the full application is still assessed", "LICO is necessary but not the only issue."],
      ["What does insurance help cover?", "Health care costs during the visit", "Private insurance reduces health-cost risk."],
      ["Who is not eligible as a principal super visa applicant?", "A sibling of a Canadian citizen", "The category is limited to parents and grandparents."],
      ["What is the host's financial undertaking?", "A promise to support the visitor during the stay", "Hosts usually confirm financial support in writing."],
      ["Which proof can support host income?", "Notice of Assessment, pay stubs, and employment letter", "Tax and employment documents commonly prove income."],
      ["How is a super visa different from parent sponsorship?", "Super visa is temporary; sponsorship seeks permanent residence", "The two processes have different goals."],
      ["Can a super visa holder study long-term without a study permit?", "No, long studies generally require a study permit", "Visitor status has study limits."],
      ["What does the applicant's passport support?", "Identity and travel document validity", "A valid passport is essential for visa issuance and travel."],
      ["Who makes the final entry decision at the border?", "A border officer", "A visa allows travel to seek entry, not unconditional admission."],
      ["Why should insurance dates align with the visit?", "Coverage must be valid for the required stay period", "Coverage timing and amount must meet current rules."],
      ["Why do families choose a super visa?", "To allow longer visits with parents or grandparents", "It is useful for extended family visits when eligibility is met."],
    ],
    2: [
      ["What belongs in a super visa invitation letter?", "Host details, relationship, support promise, visit purpose, and accommodation", "A complete letter connects family, finances, and visit purpose."],
      ["How is family size relevant to LICO?", "It determines the income threshold", "LICO is calculated using household and invited-person counts."],
      ["Which income document is especially common?", "CRA Notice of Assessment", "A NOA is a common proof of declared Canadian income."],
      ["What should be checked in insurance?", "Coverage amount, duration, provider eligibility, and applicant name", "The policy must meet IRCC requirements."],
      ["Why are birth certificates often used?", "They prove the parent-child relationship chain", "Civil documents establish the qualifying relationship."],
      ["How should name differences be handled?", "Provide marriage, name-change, or explanation documents", "Name differences should be reconciled with evidence."],
      ["Which evidence can support home-country ties?", "Property, family, employment, pension, or community obligations", "Tie evidence supports temporary intent."],
      ["Why present travel history accurately?", "It helps officers assess past visa compliance", "Omissions can damage credibility."],
      ["What support can a host document besides income?", "Accommodation and living support", "Hosts can explain where the visitor will stay and how costs will be covered."],
      ["Why avoid non-refundable tickets too early?", "Visa approval and entry are not guaranteed", "Travel plans should account for processing uncertainty."],
      ["Which applicant documents support identity and civil status?", "Passport and marriage certificate if applicable", "Identity and family documents establish background."],
      ["How can a retired parent show finances?", "Pension, savings, property, and family support evidence", "Retired applicants can document economic ties and stability."],
      ["What if the host recently changed jobs?", "Provide current employment proof and income history", "Current and historical evidence can show LICO is still met."],
      ["What makes a super visa application stronger?", "Clear purpose of visit with realistic duration and support", "A credible temporary plan helps address officer concerns."],
      ["What should happen after a medical request?", "Complete the exam with an approved panel physician by the deadline", "IRCC medicals must be completed with panel physicians."],
      ["Why is host marital status relevant?", "Spouse and dependants may affect family size", "Household composition affects the income threshold."],
      ["What if both parents apply together?", "Family size and support evidence must account for both", "Inviting multiple people raises the LICO calculation."],
      ["What can prove the host resides in Canada?", "Lease, utility bill, or employment letter", "Residence evidence supports the host's ability to receive visitors."],
      ["Why must forms list family accurately?", "Incorrect family information can create credibility issues", "Truthful family disclosure is required."],
      ["What should a self-employed host provide?", "Tax filings, business income records, and financial documents", "Self-employed income should be clearly documented."],
      ["How can a grandparent relationship be proven?", "Birth certificates linking grandparent to parent to grandchild", "A document chain may be needed."],
      ["Why review insurance cancellation terms?", "Families should understand refunds and policy compliance", "The policy must meet IRCC rules and practical needs."],
      ["Why upload the applicant's financial evidence?", "It supports ties, travel ability, and temporary intent", "Applicant finances complement host support."],
      ["How are other relatives handled?", "They may need separate visitor options", "The super visa is only for parents and grandparents."],
      ["What is good practice before submission?", "Cross-check names, dates, insurance, LICO, relationship proof, and forms", "A consistency review reduces avoidable problems."],
    ],
    3: [
      ["Why can a prior overstay affect a super visa?", "It raises concerns about compliance with temporary status", "Past compliance is relevant to future temporary resident decisions."],
      ["What is risky about an indefinite visit plan?", "It can weaken temporary intent", "Super visa holders remain temporary residents."],
      ["Why must host income evidence be current?", "Officers must be satisfied LICO is met at assessment", "Current reliable income evidence is central."],
      ["What is complex for hosts with variable income?", "Proving stable income above LICO despite fluctuations", "Commission or self-employment income may need stronger documents."],
      ["Why disclose previous refusals?", "Undisclosed refusals can lead to misrepresentation findings", "Immigration history must be complete and truthful."],
      ["What if insurance is from a non-qualifying provider?", "The application may fail the insurance requirement", "Provider and coverage rules must be satisfied."],
      ["Why respect border entry conditions after approval?", "Stay length and conditions are determined at entry and by law", "Visa approval does not remove visitor conditions."],
      ["What if a super visa holder works without authorization?", "It can jeopardize status and future applications", "Visitor status does not authorize work."],
      ["Why is medical inadmissibility still relevant?", "Insurance does not eliminate health admissibility assessment", "IRCC may still assess medical admissibility."],
      ["How should weak home ties be addressed?", "Provide concrete evidence of obligations, assets, family, and return reasons", "Specific evidence is stronger than general promises."],
      ["What is risky about relying only on host documents?", "The applicant's own temporary intent may remain unproven", "Both host eligibility and applicant circumstances matter."],
      ["Why can family-size errors cause refusal?", "They may make LICO appear met when it is not", "Accurate household counts are essential."],
      ["What if host income is below LICO?", "Do not claim eligibility until qualifying income exists", "False or insufficient income evidence creates refusal risk."],
      ["Why does the officer examine visit purpose?", "To decide whether the plan is credible and temporary", "Purpose of visit is a core temporary resident factor."],
      ["Which issue may need an explanation letter?", "Previous refusal, name discrepancy, or unusually long intended stay", "Explanation letters clarify facts that may concern an officer."],
      ["What is the risk of altered bank statements?", "Refusal and possible inadmissibility", "Fraudulent documents are serious immigration violations."],
      ["Why can frequent long stays be scrutinized?", "They may suggest living in Canada rather than visiting", "The person must remain a temporary resident visitor."],
      ["How should a previous super visa refusal be addressed?", "Identify refusal reasons and submit new evidence addressing them", "A reapplication should respond directly to earlier concerns."],
      ["Why avoid overstating support capacity?", "Unrealistic claims can undermine credibility", "Support promises should match documented income and obligations."],
      ["What if a parent has limited property or employment abroad?", "The file may need stronger family, financial, and social tie evidence", "Weak economic ties can be balanced with other credible return reasons."],
      ["What is procedural fairness in a super visa case?", "A chance to respond to serious concerns such as misrepresentation", "A timely evidence-based response is important."],
      ["Why can incomplete family disclosure affect future sponsorship?", "It can create credibility and eligibility problems later", "Family information should be complete and consistent."],
      ["What before extending a stay beyond authorized time?", "Apply to extend visitor status before expiry", "Visitors must maintain status if staying longer."],
      ["Why is refusal analysis useful before reapplying?", "It targets actual weaknesses instead of random documents", "Understanding refusal grounds supports a better application."],
      ["What is the best strategy for a complex super visa file?", "Prove host eligibility, applicant ties, admissibility, and temporary purpose", "Complex cases need evidence for every likely officer concern."],
    ],
  },
  caips: {
    1: [
      ["What are CAIPS or GCMS notes?", "Internal immigration file notes released through an access request", "CAIPS is older terminology; GCMS notes help explain IRCC file history."],
      ["What does GCMS stand for?", "Global Case Management System", "GCMS is IRCC's case management system."],
      ["Why request GCMS notes after refusal?", "To understand officer concerns and refusal reasoning", "Notes can reveal details beyond a standard refusal letter."],
      ["What does ATIP stand for?", "Access to Information and Privacy", "ATIP is the process for requesting government records."],
      ["Who can usually make an ATIP request directly?", "A Canadian citizen, permanent resident, or person/entity in Canada", "Access requests usually require a qualified requester."],
      ["What is a consent form used for?", "Authorizing release of the applicant's information to the requester", "Consent is needed when someone requests another person's personal records."],
      ["What is the common ATIP response target?", "About 30 days, subject to extensions", "ATIP is associated with a 30-day target, but extensions and delays occur."],
      ["Do GCMS notes overturn a refusal by themselves?", "No, they provide information only", "Notes are diagnostic and do not reopen or approve a file automatically."],
      ["Which file types can notes help analyze?", "Visitor, study, work, PR, sponsorship, and citizenship-related files", "GCMS notes can be useful across many immigration file types."],
      ["What information helps locate a file?", "UCI, application number, name, and date of birth", "Accurate identifiers help locate the correct record."],
      ["What is a UCI?", "Unique Client Identifier", "A UCI is an IRCC client number."],
      ["What can officer notes contain?", "Assessment comments, concerns, eligibility review, and processing history", "Notes may show how documents and eligibility were assessed."],
      ["Why might information be redacted?", "Law permits withholding sensitive or third-party information", "Access laws allow exemptions for security, privacy, and other protected information."],
      ["What is CAIPS older terminology linked to?", "Legacy immigration computer notes", "People still say CAIPS, but many modern records are GCMS."],
      ["When are GCMS notes especially helpful?", "After a refusal or long delay where reasons are unclear", "Notes can identify real issues in refusals or delays."],
      ["What fee is commonly associated with access requests?", "A small government fee", "Access to Information requests usually involve a modest fee."],
      ["Which document proves consent for a representative request?", "Signed consent from the applicant", "Signed consent authorizes disclosure to the requester."],
      ["What is refusal analysis?", "Reviewing the decision record to identify weaknesses and next steps", "Analysis compares reasons, documents, and notes."],
      ["Can notes show eligibility status?", "They may show assessments such as eligibility, criminality, or security", "Internal statuses often appear, though some fields may be redacted."],
      ["Why must request details be accurate?", "Wrong details can delay or misdirect the request", "Accurate identifiers prevent incomplete results."],
      ["How does a refusal letter compare with GCMS notes?", "It usually gives a shorter summary", "GCMS notes can provide more internal detail."],
      ["Which agency commonly holds IRCC application notes?", "Immigration, Refugees and Citizenship Canada", "IRCC holds many immigration application records."],
      ["What can a representative do with notes?", "Advise on reapplication, reconsideration, or litigation strategy", "Notes support strategy but do not decide the case."],
      ["Why is the application number useful?", "It identifies the specific application", "Application numbers help target the exact file."],
      ["Which statement about notes is correct?", "They are useful but may be redacted, delayed, or limited", "Notes provide transparency but not every desired detail."],
    ],
    2: [
      ["What is first before requesting notes for someone else?", "Obtain signed consent from the applicant", "Privacy rules require authorization for third-party release."],
      ["Which details should be collected for ATIP?", "Full name, date of birth, UCI, application number, and file type", "Complete identifiers help find the correct records."],
      ["Why choose the correct institution?", "The request must go to the department holding the records", "IRCC notes should generally be requested from IRCC."],
      ["What should be reviewed with GCMS notes?", "The refusal letter and full submitted application package", "Comparing all records gives a better diagnosis."],
      ["Why can recent notes be incomplete?", "System updates may not capture every detail immediately", "Timing affects what appears in released notes."],
      ["How can notes help before reapplying?", "They target new evidence to actual officer concerns", "A reapplication can be more focused and responsive."],
      ["What does a consent form commonly include?", "Applicant identity, requester details, signature, and scope", "Consent should clearly authorize release."],
      ["Why might ATIP extend beyond 30 days?", "Large volume, consultations, or allowed operational reasons", "Access laws permit extensions in certain cases."],
      ["Which field may reveal the deciding concern?", "Eligibility or final assessment comments", "Assessment comments often explain why the officer was not satisfied."],
      ["How are notes different from reconsideration?", "Notes disclose records; reconsideration asks IRCC to revisit a decision", "They are separate processes."],
      ["When might CBSA notes be useful?", "When border, enforcement, or security records may be relevant", "Some records are held by CBSA rather than IRCC."],
      ["How should redactions be treated?", "Recognize legal limits and infer cautiously", "Redactions limit certainty."],
      ["Why is the original package important?", "It shows what evidence the officer had", "Analysis must consider the record before the decision-maker."],
      ["What can a criminality or medical status field indicate?", "A processing stage or assessment result", "GCMS statuses can show progress or concerns in context."],
      ["How should weak-ties notes be used?", "Add specific home-country evidence and explain temporary purpose", "New evidence should address the identified concern."],
      ["What does insufficient-funds language suggest?", "The officer was not satisfied finances supported the application", "Financial concerns need clearer credible evidence."],
      ["Why do timelines matter in refusal analysis?", "They separate facts before the decision from later changes", "Old and new evidence support different strategies."],
      ["What if the wrong file is returned?", "Submit a corrected request with accurate identifiers", "Correct details help obtain the intended record."],
      ["Which next step may be time-sensitive?", "Judicial review deadline", "Court deadlines can be short and are not paused by ATIP."],
      ["Why not wait for notes if a legal deadline is near?", "Missing the deadline may eliminate that remedy", "ATIP requests do not necessarily extend court deadlines."],
      ["What is a focused ATIP request?", "A request specifying the file, period, and records needed", "Focused requests reduce confusion."],
      ["What can an in-Canada requester do?", "Submit an access request with the applicant's consent", "A qualified requester can request records but cannot decide the case."],
      ["Which document anchors refusal analysis?", "The refusal letter with date and application number", "The refusal letter identifies the specific decision."],
      ["Why might multiple ATIP requests be needed?", "Different applications or agencies may have separate records", "Complex histories can require targeted requests."],
      ["What should a refusal analysis conclude?", "Specific weaknesses, evidence gaps, and viable next options", "Useful analysis turns notes into practical strategy."],
    ],
    3: [
      ["Why can notes be insufficient for judicial review alone?", "Court review has its own record and legal reasonableness test", "GCMS notes help strategy but do not replace litigation rules."],
      ["What is risky about assuming redacted security content is harmless?", "Missing content may affect admissibility analysis", "Redactions limit visibility into sensitive assessments."],
      ["How can notes reveal document credibility issues?", "They may mention verification concerns or inconsistencies", "Officer comments can point to authenticity concerns."],
      ["Why should reapplications not merely argue the officer was wrong?", "They should provide stronger evidence addressing concerns", "Fixing evidence gaps is usually more useful than disagreement alone."],
      ["What is a limitation for very recent applications?", "Notes may show little activity if no substantive review occurred", "Notes only reflect records created by extraction."],
      ["What can study permit notes expose?", "Doubts about study plan, finances, ties, or progression", "Notes clarify temporary resident concerns."],
      ["What can sponsorship notes expose?", "Relationship genuineness, document gaps, or interview concerns", "Family-class notes may show relationship and admissibility analysis."],
      ["What is the danger of using notes to craft false evidence?", "Misrepresentation and long-term inadmissibility", "Notes should guide truthful clarification only."],
      ["Why read notes with program law in mind?", "Officer concerns must be mapped to the legal test", "Good analysis connects facts, law, and reasoning."],
      ["What suggests reconsideration may be difficult?", "The refusal was based on missing evidence not submitted before decision", "Reconsideration is harder when the original record was incomplete."],
      ["When may reconsideration be more plausible?", "When evidence was overlooked or a clear error occurred", "Reconsideration is strongest on existing-record errors."],
      ["Why are extraction dates important?", "They show when the notes snapshot was generated", "The generation date affects interpretation."],
      ["What is a common interpretation issue?", "Distinguishing boilerplate from officer-specific reasoning", "Not every GCMS line is a substantive finding."],
      ["Why can boilerplate refusal reasons mislead?", "They may not identify precise concerns without internal notes", "Generic reasons often require deeper analysis."],
      ["What if notes contradict the refusal letter?", "Analyze both and consider legal advice on reasonableness or fairness", "Contradictions can matter in context."],
      ["Why do ATIP extensions matter strategically?", "They may delay notes beyond reapplication or court planning deadlines", "Timing affects how notes can be used."],
      ["Which notes are most useful for diagnosis?", "Latest eligibility and final decision comments", "Final comments usually contain the clearest reasoning."],
      ["What can a bring-forward date indicate?", "An internal file review or action date", "Internal dates are not guaranteed decision dates."],
      ["Why separate old evidence from new evidence?", "It matters whether the officer had the evidence when deciding", "Legal options differ based on the decision record."],
      ["What is a risk of filing repeated ATIP requests too broadly?", "Delays and unfocused records that are hard to analyze", "Targeted requests are usually more useful."],
      ["How can notes help identify unreasonable reasoning?", "They may show conclusions unsupported by the submitted record", "Legal review focuses on whether reasons and outcome are justified."],
      ["Why should applicants preserve submitted packages?", "They are needed to compare with officer notes", "Without the package, refusal analysis is incomplete."],
      ["What if notes show an officer misunderstood a document?", "A targeted reconsideration or reapplication explanation may address it", "The response depends on timing and available remedies."],
      ["Why should analysis avoid overpromising based on notes?", "Notes can be partial, redacted, or ambiguous", "Responsible advice recognizes uncertainty."],
      ["What is the best advanced use of CAIPS/GCMS notes?", "Build an evidence-based strategy for reapplication, reconsideration, or review", "Notes are most useful when translated into a concrete next step."],
    ],
  },
  "spouse-dependent-owp": {
    1: [
      ["What is a spouse or dependent open work permit?", "An open work permit for an eligible spouse or partner of a qualifying worker or student", "The permit can allow the spouse or partner to work for most employers."],
      ["What is the key advantage of an open work permit?", "It is not tied to one named employer", "Open permits provide labour-market flexibility subject to conditions."],
      ["Which relationship is commonly relevant?", "Spouse or common-law partner", "Eligibility usually depends on a genuine qualifying relationship."],
      ["Can dependent children always get open work permits through this category?", "No, children's options depend on age, status, and program rules", "Dependent children may need visitor, study, or other authorization depending on facts."],
      ["What does C41 commonly relate to?", "Spouses of certain skilled workers", "C41 has been used for spouse open work permit eligibility connected to skilled workers."],
      ["What does C42 commonly relate to?", "Spouses of certain international students", "C42 has been used for spouse open work permits connected to qualifying students."],
      ["Does an open work permit guarantee entry to Canada?", "No, entry is still assessed separately", "A permit approval does not remove admissibility or border assessment."],
      ["Who issues spouse open work permits?", "Immigration, Refugees and Citizenship Canada", "IRCC assesses and issues work permits."],
      ["What must the principal worker or student usually have?", "Valid status and qualifying work or study circumstances", "The spouse's eligibility depends on the principal applicant's qualifying situation."],
      ["Which document proves marriage?", "Marriage certificate", "Civil status documents help prove the spousal relationship."],
      ["How is common-law partnership usually shown?", "Cohabitation and shared-life evidence for the required period", "Common-law cases need evidence beyond a simple statement."],
      ["What type of work permit is the spouse permit normally?", "Open work permit", "It usually allows work for most employers."],
      ["Does a spouse OWP require an LMIA?", "No, it is generally LMIA-exempt when eligibility is met", "The category relies on an exemption rather than a labour market test."],
      ["Can a spouse OWP holder work for any employer without limits?", "Most employers, subject to printed conditions and restricted sectors", "Open permits still include conditions such as medical restrictions."],
      ["What is a dependent child in immigration terms?", "A child meeting IRCC age and dependency rules", "Dependent-child status is defined by regulation and policy."],
      ["Why is the principal applicant's status important?", "It is the basis for the spouse's eligibility", "If the principal does not qualify, the spouse application may fail."],
      ["What does OWP stand for?", "Open Work Permit", "OWP is the abbreviation for open work permit."],
      ["Is a job offer usually required for a spouse OWP?", "No, not usually", "The permit is open and normally not based on a specific employer."],
      ["What should a spouse OWP applicant prove about the relationship?", "That it is genuine and legally recognized or common-law", "Relationship credibility is central to the application."],
      ["Can spouses apply from outside Canada?", "Yes, if they meet the rules for their situation", "Location can affect forms and travel documents but does not by itself prove eligibility."],
      ["What is a principal applicant in this context?", "The worker or student whose status supports the spouse's application", "The spouse's application is derivative of the principal's qualifying status."],
      ["What happens when the principal permit expires soon?", "The spouse permit may be limited or refused if eligibility is not durable", "Validity often follows the principal applicant's authorization."],
      ["What does a spouse OWP not grant by itself?", "Permanent residence", "It is temporary worker status, not PR."],
      ["Why check current IRCC rules before applying?", "Spouse OWP eligibility categories change over time", "Policy changes can affect workers, students, and family members."],
      ["Which proof is useful for a spouse of a worker?", "Principal worker's permit, job details, and proof of employment", "The application must show the principal worker qualifies."],
    ],
    2: [
      ["What should be included for a spouse of a skilled worker?", "Principal work permit, employment letter, pay stubs, and relationship proof", "Evidence should show both qualifying employment and a genuine relationship."],
      ["What should be included for a spouse of a student?", "Study permit, enrollment proof, program details, and relationship proof", "The student spouse's eligibility depends on qualifying study circumstances."],
      ["Why are pay stubs useful?", "They show the principal worker is actively employed", "Active employment evidence can support worker-based eligibility."],
      ["Why is an enrollment letter useful?", "It confirms the principal student is actively studying in a qualifying program", "Student-based spouse OWPs require evidence of qualifying study."],
      ["How should a common-law couple document cohabitation?", "Lease, bills, IDs, bank records, and affidavits where appropriate", "Multiple records can prove shared residence and partnership."],
      ["What if the marriage is recent?", "Provide stronger evidence of relationship history and genuineness", "Recent marriages may need more context and supporting documents."],
      ["Which forms should be consistent?", "Names, dates, addresses, family information, and status details", "Consistency reduces credibility concerns."],
      ["Why is passport validity important?", "The work permit cannot be issued beyond passport validity", "A short passport can shorten the spouse permit."],
      ["What is maintained status for a spouse OWP extension?", "Status that may continue after a timely extension application", "Timely filing can preserve conditions while a decision is pending."],
      ["When should an extension be filed?", "Before current status expires", "Late filing can create restoration issues and work interruptions."],
      ["What if the principal changes jobs?", "Check whether the new job still supports spouse OWP eligibility", "Eligibility can depend on the principal's current employment."],
      ["What if the principal stops studying?", "The spouse's eligibility may be affected", "Student-based spouse eligibility depends on active qualifying study."],
      ["What role do dependent children documents play?", "They prove identity, age, relationship, and needed status", "Children's applications must fit their own status needs."],
      ["Can a spouse OWP be applied for with the principal's extension?", "Often yes, if both applications are properly supported", "Families commonly coordinate extensions."],
      ["Why include proof of funds?", "To show the family can support themselves temporarily", "Financial evidence can support temporary resident assessment."],
      ["What is the purpose of a letter of explanation?", "To connect relationship, principal eligibility, and family plan", "A concise explanation helps officers understand the basis for eligibility."],
      ["Why check medical exam requirements?", "Certain jobs or residence histories may require medicals", "Medical conditions can appear on open work permits."],
      ["What travel document may be needed in addition to OWP approval?", "A TRV or eTA, depending on nationality", "Work authorization and travel authorization are separate."],
      ["How should previous refusals be handled?", "Disclose them accurately and address the reasons", "Omissions can create misrepresentation concerns."],
      ["What if the principal's job is not skilled enough under current rules?", "The spouse OWP may not qualify under worker-based criteria", "Worker-based eligibility depends on the principal's qualifying occupation or category."],
      ["What if the student's program is not eligible under current rules?", "The spouse OWP may be refused", "Student-based eligibility depends on program and policy criteria."],
      ["Why are children's school plans relevant?", "Children may need study authorization or visitor status depending on age and province", "Dependent children require their own status analysis."],
      ["What should be uploaded for identity?", "Passport bio pages and civil status documents", "Identity documents anchor the application."],
      ["Why does the principal's permit length matter?", "The spouse OWP validity often follows it", "A short principal permit can limit the spouse permit."],
      ["What is a good final review step?", "Confirm relationship proof, principal eligibility, forms, fees, and status dates", "A consistency review reduces avoidable refusal risks."],
    ],
    3: [
      ["What is the risk of a non-genuine relationship finding?", "Refusal and possible misrepresentation concerns", "Relationship credibility is central and false claims are serious."],
      ["Why can C41 or C42 coding matter?", "The exemption code must match the principal applicant's qualifying situation", "Wrong coding can confuse eligibility and processing."],
      ["What if the principal worker is between jobs?", "Spouse eligibility may be difficult without active qualifying employment", "Worker-based spouse eligibility often depends on current qualifying work."],
      ["Why can unpaid leave by the principal worker matter?", "It may raise questions about active employment", "Pay and employment records can affect eligibility analysis."],
      ["What if the principal student's program changes?", "The spouse's eligibility should be reassessed under current rules", "Program changes can affect student-based OWP eligibility."],
      ["Why is unauthorized work by the spouse risky?", "It can affect status, extensions, and future applications", "Work must match authorization and permit conditions."],
      ["What if the principal loses status?", "The spouse's derivative eligibility and family status plan may be affected", "Derivative work permits depend on the principal's valid qualifying status."],
      ["Why should family members avoid inconsistent address histories?", "Inconsistencies can undermine relationship and cohabitation evidence", "Address records help prove shared life and truthful disclosure."],
      ["What is the risk of hiding a prior marriage or child?", "Misrepresentation and family admissibility problems", "Complete family disclosure is required."],
      ["How should a previous spouse OWP refusal be addressed?", "Identify the concerns and submit targeted new evidence", "Reapplications should respond directly to refusal reasons."],
      ["What if a principal worker's NOC or TEER is borderline?", "Provide duties and employment evidence showing the category qualifies", "Eligibility depends on actual job facts and current rules."],
      ["Why can self-employed principal work be complex?", "It may not satisfy worker-based spouse eligibility without clear qualifying evidence", "Self-employment needs careful policy and evidence review."],
      ["What is the issue with a very short remaining principal permit?", "The spouse permit may be short or eligibility may look weak", "Permit validity and family plans should be timed carefully."],
      ["Why can dependent children's age matter?", "Dependency rules and available status options depend on age", "Children's status must be assessed separately."],
      ["What if a child wants to work in Canada?", "They need their own work authorization if eligible", "A parent's spouse OWP does not automatically authorize child employment."],
      ["Why is medical restriction compliance important?", "Some open permits restrict work in health, childcare, or similar fields", "A medical exam may be needed to remove certain restrictions."],
      ["What if the spouse works for an ineligible employer listed by IRCC?", "It can breach open work permit conditions", "Open permits still prohibit work for certain employers or sectors."],
      ["Why should applicants disclose separation or relationship breakdown?", "It may affect eligibility and truthfulness of the application", "The relationship must be genuine and continuing where required."],
      ["What is a procedural fairness concern in spouse OWP files?", "Doubts about relationship genuineness or document authenticity", "A PFL should be answered with precise evidence."],
      ["Why avoid template-only relationship letters?", "They may fail to prove the couple's specific history", "Specific credible evidence is stronger than generic statements."],
      ["What if the principal switches from study to PGWP?", "The spouse's eligibility should be reassessed under worker-spouse rules", "Changing principal status can change the spouse's eligibility basis."],
      ["Why can timing matter when applying with a principal extension?", "A refusal or delay in the principal file can affect the spouse file", "Family applications are connected when eligibility is derivative."],
      ["How should conflicting marital-status records be handled?", "Correct and explain them with civil documents", "Unresolved conflicts can create credibility concerns."],
      ["What if the spouse's passport expires before the requested permit period?", "The permit may be shortened to passport validity", "IRCC generally cannot issue beyond passport expiry."],
      ["What is the best strategy for a complex spouse OWP file?", "Document the relationship, principal eligibility, status history, and child status needs", "Complex family files need a complete evidence-based narrative."],
    ],
  },
};

export const BANKS = Object.fromEntries(
  Object.entries(rows).map(([service, levels]) => [
    service,
    Object.fromEntries(
      Object.entries(levels).map(([level, levelRows]) => [
        level,
        makeLevel(Number(level), levelRows, distractors[service]),
      ]),
    ),
  ]),
);
