-- Eligibility questions: 07-eu-ireland
-- Regenerate: node scripts/generate-eligibility-questions-sql-split.mjs

INSERT INTO public.service_eligibility_questions
  (library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
SELECT v.library_id, v.code, v.section, v.label, v.help_text, v.q_type, v.options, v.conditional_on, v.rule, v.prefill_field, v.allows_pending_note, v.sort_order
FROM (VALUES
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'cas_from_licensed_ireland_sponsor', 'eligibility', 'Does the client meet: CAS from licensed Ireland sponsor?', 'CAS number valid and unused', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 10),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'financial_requirement_met_28_day_rule', 'eligibility', 'Does the client meet: Financial requirement met (28-day rule)?', 'Funds held 28 consecutive days', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 20),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'english_language_at_selt_level_if_requir', 'eligibility', 'Does the client meet: English language at SELT level (if required)?', 'IELTS Irish Immigration Service Delivery or exempt pathway', 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 30),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'tb_test_certificate_if_applicable', 'eligibility', 'Does the client meet: TB test certificate (if applicable)?', 'Required for Indian nationals', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'atas_certificate_if_course_requires', 'eligibility', 'Does the client meet: ATAS certificate (if course requires)?', 'Check CAS and course code', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'genuine_student_credible_study_plan', 'eligibility', 'Does the client meet: Genuine student / credible study plan?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 60),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'immigration_history_disclosed', 'eligibility', 'Does the client meet: Immigration history disclosed?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 80),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 90),
  ('b2000001-0001-4000-8000-0000000000a3'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 100),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'valid_passport', 'eligibility', 'Does the client meet: Valid passport?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'clear_visit_purpose', 'eligibility', 'Does the client meet: Clear visit purpose?', 'Tourism, family, or permitted business activity', 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'proof_of_funds', 'eligibility', 'Does the client meet: Proof of funds?', 'Cover trip cost or credible sponsor', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'strong_ties_to_india', 'eligibility', 'Does the client meet: Strong ties to India?', 'Employment, business, property, family', 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 40),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'accommodation_and_travel_plans', 'eligibility', 'Does the client meet: Accommodation and travel plans?', 'Itinerary or host invitation', 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 50),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'biometrics_completed', 'eligibility', 'Does the client meet: Biometrics completed?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 60),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'no_prior_immigration_breaches_undisclose', 'eligibility', 'Does the client meet: No prior immigration breaches undisclosed?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 80),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 90),
  ('b2000001-0001-4000-8000-0000000000a4'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 100)
) AS v(library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.service_eligibility_questions q
  WHERE q.library_id = v.library_id AND q.code = v.code
);
