-- Eligibility questions: 07-eu-poland
-- Regenerate: node scripts/generate-eligibility-questions-sql-split.mjs

INSERT INTO public.service_eligibility_questions
  (library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
SELECT v.library_id, v.code, v.section, v.label, v.help_text, v.q_type, v.options, v.conditional_on, v.rule, v.prefill_field, v.allows_pending_note, v.sort_order
FROM (VALUES
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'admission_from_recognised_poland_institu', 'eligibility', 'Does the client meet: Admission from recognised Poland institution?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 10),
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'proof_of_funds_for_study_period', 'eligibility', 'Does the client meet: Proof of funds for study period?', 'Verify current amount on official portal', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 20),
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'health_insurance_travel_statutory', 'eligibility', 'Does the client meet: Health insurance (travel + statutory)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'motivation_letter_and_cv', 'eligibility', 'Does the client meet: Motivation letter and CV?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 40),
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'language_proficiency_as_required', 'eligibility', 'Does the client meet: Language proficiency (as required)?', 'English or local language per program', 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 50),
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'valid_passport', 'eligibility', 'Does the client meet: Valid passport?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 60),
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 70),
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000dc'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 90),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'valid_passport_3_months_beyond_stay', 'eligibility', 'Does the client meet: Valid passport (3+ months beyond stay)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'travel_medical_insurance_30_000', 'eligibility', 'Does the client meet: Travel medical insurance €30,000+?', 'Valid for entire Schengen stay', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 20),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'proof_of_accommodation_and_itinerary', 'eligibility', 'Does the client meet: Proof of accommodation and itinerary?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'proof_of_funds', 'eligibility', 'Does the client meet: Proof of funds?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'strong_ties_to_india', 'eligibility', 'Does the client meet: Strong ties to India?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 50),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'cover_letter_explaining_purpose', 'eligibility', 'Does the client meet: Cover letter explaining purpose?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 60),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'biometrics_if_not_in_vis', 'eligibility', 'Does the client meet: Biometrics (if not in VIS)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 70),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 80),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 90),
  ('b2000001-0001-4000-8000-0000000000dd'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 100),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'valid_marriage_certificate_apostilled_tr', 'eligibility', 'Does the client meet: Valid marriage certificate (apostilled/translated)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'sponsor_legal_status_in_destination_coun', 'eligibility', 'Does the client meet: Sponsor legal status in destination country?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 20),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'proof_of_genuine_relationship', 'eligibility', 'Does the client meet: Proof of genuine relationship?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'sponsor_adequate_income_and_housing', 'eligibility', 'Does the client meet: Sponsor adequate income and housing?', 'Verify current thresholds', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'health_insurance_coverage', 'eligibility', 'Does the client meet: Health insurance coverage?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'language_integration_requirements_if_app', 'eligibility', 'Does the client meet: Language/integration requirements (if applicable)?', 'Country-specific exemptions may apply', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 60),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 70),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000de'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 90),
  ('b2000001-0001-4000-8000-0000000000df'::uuid, 'university_degree_recognised_in_poland', 'eligibility', 'Does the client meet: University degree recognised in Poland?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000df'::uuid, 'job_offer_meets_blue_card_salary_thresho', 'eligibility', 'Does the client meet: Job offer meets Blue Card salary threshold?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 20),
  ('b2000001-0001-4000-8000-0000000000df'::uuid, 'contract_duration_and_role_details_docum', 'eligibility', 'Does the client meet: Contract duration and role details documented?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000df'::uuid, 'health_insurance_arranged', 'eligibility', 'Does the client meet: Health insurance arranged?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000df'::uuid, 'work_authorisation_route_confirmed_with_', 'eligibility', 'Does the client meet: Work authorisation route confirmed with employer?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 50),
  ('b2000001-0001-4000-8000-0000000000df'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000df'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000df'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80)
) AS v(library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.service_eligibility_questions q
  WHERE q.library_id = v.library_id AND q.code = v.code
);
