-- Eligibility questions: 08-other
-- Regenerate: node scripts/generate-eligibility-questions-sql-split.mjs

INSERT INTO public.service_eligibility_questions
  (library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
SELECT v.library_id, v.code, v.section, v.label, v.help_text, v.q_type, v.options, v.conditional_on, v.rule, v.prefill_field, v.allows_pending_note, v.sort_order
FROM (VALUES
  ('b2000001-0001-4000-8000-0000000000d1'::uuid, 'bachelor_s_degree_or_qualifying_pre_med_', 'eligibility', 'Does the client meet: Bachelor''s degree or qualifying pre-med coursework?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000d1'::uuid, 'english_proficiency_if_required', 'eligibility', 'Does the client meet: English proficiency (if required)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000d1'::uuid, 'neet_qualified_indian_applicants_verify_', 'eligibility', 'Does the client meet: NEET qualified (Indian applicants — verify current NMC rule)?', 'Check NMC notification at admission year', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000d1'::uuid, 'meet_susom_admission_requirements', 'eligibility', 'Does the client meet: Meet SUSOM admission requirements?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000d1'::uuid, 'financial_capacity_for_full_program', 'eligibility', 'Does the client meet: Financial capacity for full program?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000d1'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000d1'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000d1'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000d2'::uuid, 'meet_university_academic_entry_requireme', 'eligibility', 'Does the client meet: Meet university academic entry requirements?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000d2'::uuid, 'english_proficiency_if_required', 'eligibility', 'Does the client meet: English proficiency (if required)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000d2'::uuid, 'neet_qualified_indian_applicants_verify_', 'eligibility', 'Does the client meet: NEET qualified (Indian applicants — verify current NMC rule)?', 'Check NMC notification at admission year', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000d2'::uuid, 'financial_capacity_for_full_program', 'eligibility', 'Does the client meet: Financial capacity for full program?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000d2'::uuid, 'age_and_health_requirements_met', 'eligibility', 'Does the client meet: Age and health requirements met?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000d2'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000d2'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000d2'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000d3'::uuid, 'meet_university_academic_entry_requireme', 'eligibility', 'Does the client meet: Meet university academic entry requirements?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000d3'::uuid, 'english_proficiency_if_required', 'eligibility', 'Does the client meet: English proficiency (if required)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000d3'::uuid, 'neet_qualified_indian_applicants_verify_', 'eligibility', 'Does the client meet: NEET qualified (Indian applicants — verify current NMC rule)?', 'Check NMC notification at admission year', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000d3'::uuid, 'financial_capacity_for_full_program', 'eligibility', 'Does the client meet: Financial capacity for full program?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000d3'::uuid, 'age_and_health_requirements_met', 'eligibility', 'Does the client meet: Age and health requirements met?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000d3'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000d3'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000d3'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000d4'::uuid, 'meet_university_academic_entry_requireme', 'eligibility', 'Does the client meet: Meet university academic entry requirements?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000d4'::uuid, 'english_proficiency_if_required', 'eligibility', 'Does the client meet: English proficiency (if required)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000d4'::uuid, 'neet_qualified_indian_applicants_verify_', 'eligibility', 'Does the client meet: NEET qualified (Indian applicants — verify current NMC rule)?', 'Check NMC notification at admission year', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000d4'::uuid, 'financial_capacity_for_full_program', 'eligibility', 'Does the client meet: Financial capacity for full program?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000d4'::uuid, 'age_and_health_requirements_met', 'eligibility', 'Does the client meet: Age and health requirements met?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000d4'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000d4'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000d4'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000d5'::uuid, 'meet_university_academic_entry_requireme', 'eligibility', 'Does the client meet: Meet university academic entry requirements?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000d5'::uuid, 'english_proficiency_if_required', 'eligibility', 'Does the client meet: English proficiency (if required)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000d5'::uuid, 'neet_qualified_indian_applicants_verify_', 'eligibility', 'Does the client meet: NEET qualified (Indian applicants — verify current NMC rule)?', 'Check NMC notification at admission year', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000d5'::uuid, 'financial_capacity_for_full_program', 'eligibility', 'Does the client meet: Financial capacity for full program?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000d5'::uuid, 'age_and_health_requirements_met', 'eligibility', 'Does the client meet: Age and health requirements met?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000d5'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000d5'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000d5'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000d6'::uuid, 'meet_university_academic_entry_requireme', 'eligibility', 'Does the client meet: Meet university academic entry requirements?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000d6'::uuid, 'english_proficiency_if_required', 'eligibility', 'Does the client meet: English proficiency (if required)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000d6'::uuid, 'neet_qualified_indian_applicants_verify_', 'eligibility', 'Does the client meet: NEET qualified (Indian applicants — verify current NMC rule)?', 'Check NMC notification at admission year', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000d6'::uuid, 'financial_capacity_for_full_program', 'eligibility', 'Does the client meet: Financial capacity for full program?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000d6'::uuid, 'age_and_health_requirements_met', 'eligibility', 'Does the client meet: Age and health requirements met?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000d6'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000d6'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000d6'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000d7'::uuid, 'meet_university_academic_entry_requireme', 'eligibility', 'Does the client meet: Meet university academic entry requirements?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000d7'::uuid, 'english_proficiency_if_required', 'eligibility', 'Does the client meet: English proficiency (if required)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000d7'::uuid, 'neet_qualified_indian_applicants_verify_', 'eligibility', 'Does the client meet: NEET qualified (Indian applicants — verify current NMC rule)?', 'Check NMC notification at admission year', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000d7'::uuid, 'financial_capacity_for_full_program', 'eligibility', 'Does the client meet: Financial capacity for full program?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000d7'::uuid, 'age_and_health_requirements_met', 'eligibility', 'Does the client meet: Age and health requirements met?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000d7'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000d7'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000d7'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80)
) AS v(library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.service_eligibility_questions q
  WHERE q.library_id = v.library_id AND q.code = v.code
);
