-- Eligibility questions: 10-singapore
-- Regenerate: node scripts/generate-eligibility-questions-sql-split.mjs

INSERT INTO public.service_eligibility_questions
  (library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
SELECT v.library_id, v.code, v.section, v.label, v.help_text, v.q_type, v.options, v.conditional_on, v.rule, v.prefill_field, v.allows_pending_note, v.sort_order
FROM (VALUES
  ('b2000001-0001-4000-8000-0000000000e7'::uuid, 'admission_from_ica_recognised_institutio', 'eligibility', 'Does the client meet: Admission from ICA-recognised institution?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 10),
  ('b2000001-0001-4000-8000-0000000000e7'::uuid, 'solar_application_submitted_by_instituti', 'eligibility', 'Does the client meet: SOLAR application submitted by institution?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 20),
  ('b2000001-0001-4000-8000-0000000000e7'::uuid, 'financial_proof_per_institution_guidelin', 'eligibility', 'Does the client meet: Financial proof per institution guidelines?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000e7'::uuid, 'medical_examination_if_required', 'eligibility', 'Does the client meet: Medical examination (if required)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000e7'::uuid, 'valid_passport_6_months', 'eligibility', 'Does the client meet: Valid passport 6+ months?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 50),
  ('b2000001-0001-4000-8000-0000000000e7'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 60),
  ('b2000001-0001-4000-8000-0000000000e7'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-0000000000e7'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'valid_passport_6_months', 'eligibility', 'Does the client meet: Valid passport (6+ months)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'passport_scan_and_photo_per_spec', 'eligibility', 'Does the client meet: Passport scan and photo per spec?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 20),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'confirmed_duration_and_entry_type_30_60_', 'eligibility', 'Does the client meet: Confirmed duration and entry type (30/60/90, single/multiple)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 30),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'emirate_route_selected_dubai_sharjah_abu', 'eligibility', 'Does the client meet: Emirate route selected (Dubai / Sharjah / Abu Dhabi)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 40),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'return_onward_travel_plan', 'eligibility', 'Does the client meet: Return/onward travel plan?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 50),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'no_prior_singapore_overstay_or_ban', 'eligibility', 'Does the client meet: No prior Singapore overstay or ban?', 'ICA history check', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 60),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'sponsor_or_authorised_agent_engaged', 'eligibility', 'Does the client meet: Sponsor or authorised agent engaged?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 70),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 80),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 90),
  ('b2000001-0001-4000-8000-0000000000e8'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 100),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'valid_marriage_certificate_apostilled_tr', 'eligibility', 'Does the client meet: Valid marriage certificate (apostilled/translated)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'sponsor_legal_status_in_destination_coun', 'eligibility', 'Does the client meet: Sponsor legal status in destination country?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 20),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'proof_of_genuine_relationship', 'eligibility', 'Does the client meet: Proof of genuine relationship?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'sponsor_adequate_income_and_housing', 'eligibility', 'Does the client meet: Sponsor adequate income and housing?', 'Verify current thresholds', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'health_insurance_coverage', 'eligibility', 'Does the client meet: Health insurance coverage?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'language_integration_requirements_if_app', 'eligibility', 'Does the client meet: Language/integration requirements (if applicable)?', 'Country-specific exemptions may apply', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 60),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 70),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000e9'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 90),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'signed_offer_from_licensed_singapore_emp', 'eligibility', 'Does the client meet: Signed offer from licensed Singapore employer?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 10),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'mom_work_permit_pre_approval_obtained', 'eligibility', 'Does the client meet: MOM work permit / pre-approval obtained?', 'Employer initiates', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 20),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'degree_experience_attested_for_singapore', 'eligibility', 'Does the client meet: Degree/experience attested for Singapore?', '4–6 weeks', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'passport_valid_6_months', 'eligibility', 'Does the client meet: Passport valid 6+ months?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 40),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'medical_fitness_singapore_panel', 'eligibility', 'Does the client meet: Medical fitness (Singapore panel)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'role_matches_qualification_skill_level', 'eligibility', 'Does the client meet: Role matches qualification (skill level)?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet"}'::jsonb, NULL, false, 60),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', 'Check expiry against expected decision timeline.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 70),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'prior_refusals', 'compliance', 'Any prior visa refusals, overstays, or undeclared immigration history?', 'Full disclosure required before lodging.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 80),
  ('b2000001-0001-4000-8000-0000000000ea'::uuid, 'counselor_ready', 'submission', 'Has the counselor confirmed the file is complete and ready to lodge?', 'Final quality check before submission.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false}}'::jsonb, NULL, false, 90)
) AS v(library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.service_eligibility_questions q
  WHERE q.library_id = v.library_id AND q.code = v.code
);
