-- Express Entry / PR eligibility assessment questions

INSERT INTO public.service_eligibility_questions
  (library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
SELECT v.library_id, v.code, v.section, v.label, v.help_text, v.q_type, v.options, v.conditional_on, v.rule, v.prefill_field, v.allows_pending_note, v.sort_order
FROM (VALUES
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'program_stream', 'program', 'Which Express Entry program stream applies?', 'FSW = foreign skilled worker; CEC = Canadian experience; FST = skilled trades.', 'select', '["Federal Skilled Worker (FSW)","Canadian Experience Class (CEC)","Federal Skilled Trades (FST)","Not sure yet"]'::jsonb, NULL::jsonb, '{"warn_if":{"equals":"Not sure yet"}}'::jsonb, NULL, false, 10),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'language_clb_met', 'language', 'Does the client meet the minimum language requirement (CLB) for the chosen stream?', 'Verify IELTS General, CELPIP, or PTE Core scores against current IRCC minimums.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet","allows_pending":true}'::jsonb, 'clients.english_overall', true, 20),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'eca_done', 'credentials', 'For FSW: is Educational Credential Assessment (ECA) completed for foreign credentials?', 'Not required for CEC/FST in the same way — answer N/A if not FSW.', 'yes_no_na', NULL::jsonb, '{"question":"program_stream","equals":"Federal Skilled Worker (FSW)"}'::jsonb, '{"block_if":{"equals":false},"outcome_if_fail":"not_yet","allows_pending":true}'::jsonb, NULL, true, 30),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'work_experience_noc', 'experience', 'Is skilled work experience documented with correct NOC/TEER for the chosen stream?', 'Include reference letters, pay slips, and NOC match review.', 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 40),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'proof_of_funds', 'funds', 'For FSW/FST: does the client meet proof-of-funds requirements?', 'Answer N/A for CEC. Verify current IRCC settlement fund thresholds.', 'yes_no_na', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, NULL, true, 50),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'crs_status', 'crs', 'What is the client''s CRS / readiness status?', 'Compare against recent general and category-based draw cut-offs before advising to proceed.', 'select', '["CRS calculated — competitive for recent draws","CRS calculated — below recent draws","CRS not calculated yet","Already received ITA"]'::jsonb, NULL::jsonb, '{"block_if":{"equals":"CRS not calculated yet"},"warn_if":{"equals":"CRS calculated — below recent draws"}}'::jsonb, NULL, false, 60),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'ee_stage', 'profile', 'What stage is the client at in Express Entry?', NULL, 'select', '["Not started — profile not created","Active profile — no ITA yet","ITA received — PR application in progress","PR application submitted (AOR received)"]'::jsonb, NULL::jsonb, '{"warn_if":{"equals":"Not started — profile not created"}}'::jsonb, NULL, false, 70),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'pnp_boost', 'pnp', 'Does the client have (or is pursuing) a provincial nomination for +600 CRS?', 'Answer N/A if not applicable.', 'yes_no_na', NULL::jsonb, NULL::jsonb, '{}'::jsonb, NULL, false, 75),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'passport_valid', 'documents', 'Is the passport valid for the expected processing period?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"warn_if":{"equals":false},"allows_pending":true}'::jsonb, 'clients.passport_expiry', true, 80),
  ('b2000001-0001-4000-8000-000000000013'::uuid, 'inadmissibility', 'compliance', 'Any inadmissibility, misrepresentation, or prior refusal issues?', NULL, 'yes_no', NULL::jsonb, NULL::jsonb, '{"senior_review_if":{"equals":true},"block_if":{"equals":true},"outcome_if_fail":"senior_review"}'::jsonb, NULL, false, 90)
) AS v(library_id, code, section, label, help_text, q_type, options, conditional_on, rule, prefill_field, allows_pending_note, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.service_eligibility_questions q
  WHERE q.library_id = v.library_id AND q.code = v.code
);
