-- India states/UTs + major cities for education/experience location dropdowns.
INSERT INTO public.master_items (list_key, code, label, sort_order, metadata) VALUES
  ('location_provinces', 'IN-AP', 'Andhra Pradesh', 110, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-AR', 'Arunachal Pradesh', 120, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-AS', 'Assam', 130, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-BR', 'Bihar', 140, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-CG', 'Chhattisgarh', 150, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-GA', 'Goa', 160, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-GJ', 'Gujarat', 170, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-HR', 'Haryana', 180, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-HP', 'Himachal Pradesh', 190, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-JH', 'Jharkhand', 200, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-KA', 'Karnataka', 210, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-KL', 'Kerala', 220, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-MP', 'Madhya Pradesh', 230, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-MH', 'Maharashtra', 240, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-MN', 'Manipur', 250, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-ML', 'Meghalaya', 260, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-MZ', 'Mizoram', 270, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-NL', 'Nagaland', 280, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-OD', 'Odisha', 290, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-PB', 'Punjab', 300, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-RJ', 'Rajasthan', 310, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-SK', 'Sikkim', 320, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-TN', 'Tamil Nadu', 330, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-TS', 'Telangana', 340, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-TR', 'Tripura', 350, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-UP', 'Uttar Pradesh', 360, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-UK', 'Uttarakhand', 370, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-WB', 'West Bengal', 380, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-AN', 'Andaman and Nicobar Islands', 390, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-CH', 'Chandigarh', 400, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-DH', 'Dadra and Nagar Haveli and Daman and Diu', 410, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-DL', 'Delhi', 420, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-JK', 'Jammu and Kashmir', 430, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-LA', 'Ladakh', 440, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-LD', 'Lakshadweep', 450, '{"country":"India","country_code":"IN"}'::jsonb),
  ('location_provinces', 'IN-PY', 'Puducherry', 460, '{"country":"India","country_code":"IN"}'::jsonb)
ON CONFLICT (list_key, code) DO UPDATE SET
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order,
  metadata = EXCLUDED.metadata;

INSERT INTO public.master_items (list_key, code, label, sort_order, metadata) VALUES
  ('location_cities', 'IN-AP-visakhapatnam', 'Visakhapatnam', 1001, '{"country":"India","province_code":"IN-AP"}'::jsonb),
  ('location_cities', 'IN-AP-vijayawada', 'Vijayawada', 1002, '{"country":"India","province_code":"IN-AP"}'::jsonb),
  ('location_cities', 'IN-AP-guntur', 'Guntur', 1003, '{"country":"India","province_code":"IN-AP"}'::jsonb),
  ('location_cities', 'IN-AP-tirupati', 'Tirupati', 1004, '{"country":"India","province_code":"IN-AP"}'::jsonb),
  ('location_cities', 'IN-AP-nellore', 'Nellore', 1005, '{"country":"India","province_code":"IN-AP"}'::jsonb),
  ('location_cities', 'IN-AR-itanagar', 'Itanagar', 1006, '{"country":"India","province_code":"IN-AR"}'::jsonb),
  ('location_cities', 'IN-AR-tawang', 'Tawang', 1007, '{"country":"India","province_code":"IN-AR"}'::jsonb),
  ('location_cities', 'IN-AR-pasighat', 'Pasighat', 1008, '{"country":"India","province_code":"IN-AR"}'::jsonb),
  ('location_cities', 'IN-AS-guwahati', 'Guwahati', 1009, '{"country":"India","province_code":"IN-AS"}'::jsonb),
  ('location_cities', 'IN-AS-dibrugarh', 'Dibrugarh', 1010, '{"country":"India","province_code":"IN-AS"}'::jsonb),
  ('location_cities', 'IN-AS-silchar', 'Silchar', 1011, '{"country":"India","province_code":"IN-AS"}'::jsonb),
  ('location_cities', 'IN-AS-jorhat', 'Jorhat', 1012, '{"country":"India","province_code":"IN-AS"}'::jsonb),
  ('location_cities', 'IN-BR-patna', 'Patna', 1013, '{"country":"India","province_code":"IN-BR"}'::jsonb),
  ('location_cities', 'IN-BR-gaya', 'Gaya', 1014, '{"country":"India","province_code":"IN-BR"}'::jsonb),
  ('location_cities', 'IN-BR-muzaffarpur', 'Muzaffarpur', 1015, '{"country":"India","province_code":"IN-BR"}'::jsonb),
  ('location_cities', 'IN-BR-bhagalpur', 'Bhagalpur', 1016, '{"country":"India","province_code":"IN-BR"}'::jsonb),
  ('location_cities', 'IN-CG-raipur', 'Raipur', 1017, '{"country":"India","province_code":"IN-CG"}'::jsonb),
  ('location_cities', 'IN-CG-bhilai', 'Bhilai', 1018, '{"country":"India","province_code":"IN-CG"}'::jsonb),
  ('location_cities', 'IN-CG-bilaspur', 'Bilaspur', 1019, '{"country":"India","province_code":"IN-CG"}'::jsonb),
  ('location_cities', 'IN-CG-durg', 'Durg', 1020, '{"country":"India","province_code":"IN-CG"}'::jsonb),
  ('location_cities', 'IN-GA-panaji', 'Panaji', 1021, '{"country":"India","province_code":"IN-GA"}'::jsonb),
  ('location_cities', 'IN-GA-margao', 'Margao', 1022, '{"country":"India","province_code":"IN-GA"}'::jsonb),
  ('location_cities', 'IN-GA-vasco-da-gama', 'Vasco da Gama', 1023, '{"country":"India","province_code":"IN-GA"}'::jsonb),
  ('location_cities', 'IN-GA-mapusa', 'Mapusa', 1024, '{"country":"India","province_code":"IN-GA"}'::jsonb),
  ('location_cities', 'IN-GJ-ahmedabad', 'Ahmedabad', 1025, '{"country":"India","province_code":"IN-GJ"}'::jsonb),
  ('location_cities', 'IN-GJ-surat', 'Surat', 1026, '{"country":"India","province_code":"IN-GJ"}'::jsonb),
  ('location_cities', 'IN-GJ-vadodara', 'Vadodara', 1027, '{"country":"India","province_code":"IN-GJ"}'::jsonb),
  ('location_cities', 'IN-GJ-rajkot', 'Rajkot', 1028, '{"country":"India","province_code":"IN-GJ"}'::jsonb),
  ('location_cities', 'IN-GJ-gandhinagar', 'Gandhinagar', 1029, '{"country":"India","province_code":"IN-GJ"}'::jsonb),
  ('location_cities', 'IN-GJ-bhavnagar', 'Bhavnagar', 1030, '{"country":"India","province_code":"IN-GJ"}'::jsonb),
  ('location_cities', 'IN-HR-gurugram', 'Gurugram', 1031, '{"country":"India","province_code":"IN-HR"}'::jsonb),
  ('location_cities', 'IN-HR-faridabad', 'Faridabad', 1032, '{"country":"India","province_code":"IN-HR"}'::jsonb),
  ('location_cities', 'IN-HR-panipat', 'Panipat', 1033, '{"country":"India","province_code":"IN-HR"}'::jsonb),
  ('location_cities', 'IN-HR-ambala', 'Ambala', 1034, '{"country":"India","province_code":"IN-HR"}'::jsonb),
  ('location_cities', 'IN-HR-rohtak', 'Rohtak', 1035, '{"country":"India","province_code":"IN-HR"}'::jsonb),
  ('location_cities', 'IN-HP-shimla', 'Shimla', 1036, '{"country":"India","province_code":"IN-HP"}'::jsonb),
  ('location_cities', 'IN-HP-dharamshala', 'Dharamshala', 1037, '{"country":"India","province_code":"IN-HP"}'::jsonb),
  ('location_cities', 'IN-HP-manali', 'Manali', 1038, '{"country":"India","province_code":"IN-HP"}'::jsonb),
  ('location_cities', 'IN-HP-solan', 'Solan', 1039, '{"country":"India","province_code":"IN-HP"}'::jsonb),
  ('location_cities', 'IN-JH-ranchi', 'Ranchi', 1040, '{"country":"India","province_code":"IN-JH"}'::jsonb),
  ('location_cities', 'IN-JH-jamshedpur', 'Jamshedpur', 1041, '{"country":"India","province_code":"IN-JH"}'::jsonb),
  ('location_cities', 'IN-JH-dhanbad', 'Dhanbad', 1042, '{"country":"India","province_code":"IN-JH"}'::jsonb),
  ('location_cities', 'IN-JH-bokaro', 'Bokaro', 1043, '{"country":"India","province_code":"IN-JH"}'::jsonb),
  ('location_cities', 'IN-KA-bengaluru', 'Bengaluru', 1044, '{"country":"India","province_code":"IN-KA"}'::jsonb),
  ('location_cities', 'IN-KA-mysuru', 'Mysuru', 1045, '{"country":"India","province_code":"IN-KA"}'::jsonb),
  ('location_cities', 'IN-KA-mangaluru', 'Mangaluru', 1046, '{"country":"India","province_code":"IN-KA"}'::jsonb),
  ('location_cities', 'IN-KA-hubballi', 'Hubballi', 1047, '{"country":"India","province_code":"IN-KA"}'::jsonb),
  ('location_cities', 'IN-KA-belagavi', 'Belagavi', 1048, '{"country":"India","province_code":"IN-KA"}'::jsonb),
  ('location_cities', 'IN-KL-kochi', 'Kochi', 1049, '{"country":"India","province_code":"IN-KL"}'::jsonb),
  ('location_cities', 'IN-KL-thiruvananthapuram', 'Thiruvananthapuram', 1050, '{"country":"India","province_code":"IN-KL"}'::jsonb),
  ('location_cities', 'IN-KL-kozhikode', 'Kozhikode', 1051, '{"country":"India","province_code":"IN-KL"}'::jsonb),
  ('location_cities', 'IN-KL-thrissur', 'Thrissur', 1052, '{"country":"India","province_code":"IN-KL"}'::jsonb),
  ('location_cities', 'IN-KL-kollam', 'Kollam', 1053, '{"country":"India","province_code":"IN-KL"}'::jsonb),
  ('location_cities', 'IN-MP-bhopal', 'Bhopal', 1054, '{"country":"India","province_code":"IN-MP"}'::jsonb),
  ('location_cities', 'IN-MP-indore', 'Indore', 1055, '{"country":"India","province_code":"IN-MP"}'::jsonb),
  ('location_cities', 'IN-MP-gwalior', 'Gwalior', 1056, '{"country":"India","province_code":"IN-MP"}'::jsonb),
  ('location_cities', 'IN-MP-jabalpur', 'Jabalpur', 1057, '{"country":"India","province_code":"IN-MP"}'::jsonb),
  ('location_cities', 'IN-MP-ujjain', 'Ujjain', 1058, '{"country":"India","province_code":"IN-MP"}'::jsonb),
  ('location_cities', 'IN-MH-mumbai', 'Mumbai', 1059, '{"country":"India","province_code":"IN-MH"}'::jsonb),
  ('location_cities', 'IN-MH-pune', 'Pune', 1060, '{"country":"India","province_code":"IN-MH"}'::jsonb),
  ('location_cities', 'IN-MH-nagpur', 'Nagpur', 1061, '{"country":"India","province_code":"IN-MH"}'::jsonb),
  ('location_cities', 'IN-MH-nashik', 'Nashik', 1062, '{"country":"India","province_code":"IN-MH"}'::jsonb),
  ('location_cities', 'IN-MH-thane', 'Thane', 1063, '{"country":"India","province_code":"IN-MH"}'::jsonb),
  ('location_cities', 'IN-MH-aurangabad', 'Aurangabad', 1064, '{"country":"India","province_code":"IN-MH"}'::jsonb),
  ('location_cities', 'IN-MN-imphal', 'Imphal', 1065, '{"country":"India","province_code":"IN-MN"}'::jsonb),
  ('location_cities', 'IN-MN-thoubal', 'Thoubal', 1066, '{"country":"India","province_code":"IN-MN"}'::jsonb),
  ('location_cities', 'IN-ML-shillong', 'Shillong', 1067, '{"country":"India","province_code":"IN-ML"}'::jsonb),
  ('location_cities', 'IN-ML-tura', 'Tura', 1068, '{"country":"India","province_code":"IN-ML"}'::jsonb),
  ('location_cities', 'IN-MZ-aizawl', 'Aizawl', 1069, '{"country":"India","province_code":"IN-MZ"}'::jsonb),
  ('location_cities', 'IN-MZ-lunglei', 'Lunglei', 1070, '{"country":"India","province_code":"IN-MZ"}'::jsonb),
  ('location_cities', 'IN-NL-kohima', 'Kohima', 1071, '{"country":"India","province_code":"IN-NL"}'::jsonb),
  ('location_cities', 'IN-NL-dimapur', 'Dimapur', 1072, '{"country":"India","province_code":"IN-NL"}'::jsonb),
  ('location_cities', 'IN-OD-bhubaneswar', 'Bhubaneswar', 1073, '{"country":"India","province_code":"IN-OD"}'::jsonb),
  ('location_cities', 'IN-OD-cuttack', 'Cuttack', 1074, '{"country":"India","province_code":"IN-OD"}'::jsonb),
  ('location_cities', 'IN-OD-rourkela', 'Rourkela', 1075, '{"country":"India","province_code":"IN-OD"}'::jsonb),
  ('location_cities', 'IN-OD-puri', 'Puri', 1076, '{"country":"India","province_code":"IN-OD"}'::jsonb),
  ('location_cities', 'IN-PB-ludhiana', 'Ludhiana', 1077, '{"country":"India","province_code":"IN-PB"}'::jsonb),
  ('location_cities', 'IN-PB-amritsar', 'Amritsar', 1078, '{"country":"India","province_code":"IN-PB"}'::jsonb),
  ('location_cities', 'IN-PB-jalandhar', 'Jalandhar', 1079, '{"country":"India","province_code":"IN-PB"}'::jsonb),
  ('location_cities', 'IN-PB-patiala', 'Patiala', 1080, '{"country":"India","province_code":"IN-PB"}'::jsonb),
  ('location_cities', 'IN-PB-mohali', 'Mohali', 1081, '{"country":"India","province_code":"IN-PB"}'::jsonb),
  ('location_cities', 'IN-RJ-jaipur', 'Jaipur', 1082, '{"country":"India","province_code":"IN-RJ"}'::jsonb),
  ('location_cities', 'IN-RJ-jodhpur', 'Jodhpur', 1083, '{"country":"India","province_code":"IN-RJ"}'::jsonb),
  ('location_cities', 'IN-RJ-udaipur', 'Udaipur', 1084, '{"country":"India","province_code":"IN-RJ"}'::jsonb),
  ('location_cities', 'IN-RJ-kota', 'Kota', 1085, '{"country":"India","province_code":"IN-RJ"}'::jsonb),
  ('location_cities', 'IN-RJ-ajmer', 'Ajmer', 1086, '{"country":"India","province_code":"IN-RJ"}'::jsonb),
  ('location_cities', 'IN-SK-gangtok', 'Gangtok', 1087, '{"country":"India","province_code":"IN-SK"}'::jsonb),
  ('location_cities', 'IN-SK-namchi', 'Namchi', 1088, '{"country":"India","province_code":"IN-SK"}'::jsonb),
  ('location_cities', 'IN-TN-chennai', 'Chennai', 1089, '{"country":"India","province_code":"IN-TN"}'::jsonb),
  ('location_cities', 'IN-TN-coimbatore', 'Coimbatore', 1090, '{"country":"India","province_code":"IN-TN"}'::jsonb),
  ('location_cities', 'IN-TN-madurai', 'Madurai', 1091, '{"country":"India","province_code":"IN-TN"}'::jsonb),
  ('location_cities', 'IN-TN-tiruchirappalli', 'Tiruchirappalli', 1092, '{"country":"India","province_code":"IN-TN"}'::jsonb),
  ('location_cities', 'IN-TN-salem', 'Salem', 1093, '{"country":"India","province_code":"IN-TN"}'::jsonb),
  ('location_cities', 'IN-TS-hyderabad', 'Hyderabad', 1094, '{"country":"India","province_code":"IN-TS"}'::jsonb),
  ('location_cities', 'IN-TS-warangal', 'Warangal', 1095, '{"country":"India","province_code":"IN-TS"}'::jsonb),
  ('location_cities', 'IN-TS-nizamabad', 'Nizamabad', 1096, '{"country":"India","province_code":"IN-TS"}'::jsonb),
  ('location_cities', 'IN-TS-karimnagar', 'Karimnagar', 1097, '{"country":"India","province_code":"IN-TS"}'::jsonb),
  ('location_cities', 'IN-TR-agartala', 'Agartala', 1098, '{"country":"India","province_code":"IN-TR"}'::jsonb),
  ('location_cities', 'IN-TR-udaipur', 'Udaipur', 1099, '{"country":"India","province_code":"IN-TR"}'::jsonb),
  ('location_cities', 'IN-UP-lucknow', 'Lucknow', 1100, '{"country":"India","province_code":"IN-UP"}'::jsonb),
  ('location_cities', 'IN-UP-kanpur', 'Kanpur', 1101, '{"country":"India","province_code":"IN-UP"}'::jsonb),
  ('location_cities', 'IN-UP-noida', 'Noida', 1102, '{"country":"India","province_code":"IN-UP"}'::jsonb),
  ('location_cities', 'IN-UP-ghaziabad', 'Ghaziabad', 1103, '{"country":"India","province_code":"IN-UP"}'::jsonb),
  ('location_cities', 'IN-UP-varanasi', 'Varanasi', 1104, '{"country":"India","province_code":"IN-UP"}'::jsonb),
  ('location_cities', 'IN-UP-agra', 'Agra', 1105, '{"country":"India","province_code":"IN-UP"}'::jsonb),
  ('location_cities', 'IN-UP-prayagraj', 'Prayagraj', 1106, '{"country":"India","province_code":"IN-UP"}'::jsonb),
  ('location_cities', 'IN-UK-dehradun', 'Dehradun', 1107, '{"country":"India","province_code":"IN-UK"}'::jsonb),
  ('location_cities', 'IN-UK-haridwar', 'Haridwar', 1108, '{"country":"India","province_code":"IN-UK"}'::jsonb),
  ('location_cities', 'IN-UK-rishikesh', 'Rishikesh', 1109, '{"country":"India","province_code":"IN-UK"}'::jsonb),
  ('location_cities', 'IN-UK-haldwani', 'Haldwani', 1110, '{"country":"India","province_code":"IN-UK"}'::jsonb),
  ('location_cities', 'IN-WB-kolkata', 'Kolkata', 1111, '{"country":"India","province_code":"IN-WB"}'::jsonb),
  ('location_cities', 'IN-WB-siliguri', 'Siliguri', 1112, '{"country":"India","province_code":"IN-WB"}'::jsonb),
  ('location_cities', 'IN-WB-durgapur', 'Durgapur', 1113, '{"country":"India","province_code":"IN-WB"}'::jsonb),
  ('location_cities', 'IN-WB-howrah', 'Howrah', 1114, '{"country":"India","province_code":"IN-WB"}'::jsonb),
  ('location_cities', 'IN-WB-asansol', 'Asansol', 1115, '{"country":"India","province_code":"IN-WB"}'::jsonb),
  ('location_cities', 'IN-AN-port-blair', 'Port Blair', 1116, '{"country":"India","province_code":"IN-AN"}'::jsonb),
  ('location_cities', 'IN-CH-chandigarh', 'Chandigarh', 1117, '{"country":"India","province_code":"IN-CH"}'::jsonb),
  ('location_cities', 'IN-DH-daman', 'Daman', 1118, '{"country":"India","province_code":"IN-DH"}'::jsonb),
  ('location_cities', 'IN-DH-silvassa', 'Silvassa', 1119, '{"country":"India","province_code":"IN-DH"}'::jsonb),
  ('location_cities', 'IN-DH-diu', 'Diu', 1120, '{"country":"India","province_code":"IN-DH"}'::jsonb),
  ('location_cities', 'IN-DL-new-delhi', 'New Delhi', 1121, '{"country":"India","province_code":"IN-DL"}'::jsonb),
  ('location_cities', 'IN-DL-delhi', 'Delhi', 1122, '{"country":"India","province_code":"IN-DL"}'::jsonb),
  ('location_cities', 'IN-DL-dwarka', 'Dwarka', 1123, '{"country":"India","province_code":"IN-DL"}'::jsonb),
  ('location_cities', 'IN-DL-rohini', 'Rohini', 1124, '{"country":"India","province_code":"IN-DL"}'::jsonb),
  ('location_cities', 'IN-DL-saket', 'Saket', 1125, '{"country":"India","province_code":"IN-DL"}'::jsonb),
  ('location_cities', 'IN-JK-srinagar', 'Srinagar', 1126, '{"country":"India","province_code":"IN-JK"}'::jsonb),
  ('location_cities', 'IN-JK-jammu', 'Jammu', 1127, '{"country":"India","province_code":"IN-JK"}'::jsonb),
  ('location_cities', 'IN-JK-anantnag', 'Anantnag', 1128, '{"country":"India","province_code":"IN-JK"}'::jsonb),
  ('location_cities', 'IN-LA-leh', 'Leh', 1129, '{"country":"India","province_code":"IN-LA"}'::jsonb),
  ('location_cities', 'IN-LA-kargil', 'Kargil', 1130, '{"country":"India","province_code":"IN-LA"}'::jsonb),
  ('location_cities', 'IN-LD-kavaratti', 'Kavaratti', 1131, '{"country":"India","province_code":"IN-LD"}'::jsonb),
  ('location_cities', 'IN-PY-puducherry', 'Puducherry', 1132, '{"country":"India","province_code":"IN-PY"}'::jsonb),
  ('location_cities', 'IN-PY-karaikal', 'Karaikal', 1133, '{"country":"India","province_code":"IN-PY"}'::jsonb)
ON CONFLICT (list_key, code) DO UPDATE SET
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order,
  metadata = EXCLUDED.metadata;
