-- Patch academy_metadata.sampleDocs for all canonical visa services
-- Regenerate JSON: node scripts/seed-sample-docs.mjs

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample LOA / DLI letter (mock)","description":"Designated Learning Institution acceptance — program and dates.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample GIC certificate (mock)","description":"SDS financial requirement — approved bank GIC.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample IELTS / PTE TRF (mock)","description":"Language scores for SDS / Non-SDS discussion.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample SOP specimen (mock)","description":"Structure for genuine student intent — course fit and career plan.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample academic transcripts (mock)","description":"Marksheets with backlogs explanation guidance.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample sponsor affidavit (mock)","description":"Parent sponsor ITR-linked financial undertaking.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'c35e6051-f40f-47bf-9cac-0a386c47a336';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample invitation / sponsor letter (mock)","description":"Host details, relationship, accommodation, and duration of stay.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample travel itinerary (mock)","description":"Flights, hotels, and day-wise plan for visitor visa credibility.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample employment / NOC letter (mock)","description":"Employer letter confirming leave, role, salary, and return to India.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample property / ties document (mock)","description":"Sale deed or tax receipt — explain home-country ties.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000011';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample marriage certificate (mock)","description":"Registered marriage proof — explain translation and notarization if needed.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample relationship timeline & photos guide (mock)","description":"Collage layout for chat logs, travel photos, and ceremony pictures.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample sponsor / undertaking letter (mock)","description":"Sponsor income, accommodation, and maintenance commitment.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample chat / communication evidence (mock)","description":"Redacted WhatsApp or email excerpts — privacy-safe specimen.","mimeType":"image/jpeg","docKind":"relationship"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000012';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample language test TRF (mock)","description":"IELTS / PTE / TOEFL layout — explain CLB or points mapping.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample ECA report (mock)","description":"WES / IQAS / ICAS credential assessment — degree equivalency page.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample employment reference letter (mock)","description":"Duties, NOC code, dates, and full-time hours on company letterhead.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample resume / CV (mock)","description":"Skilled migration format — chronological roles and NOC alignment.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample nomination / job offer letter (mock)","description":"PNP nomination or employer-backed offer where applicable.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000013';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample completion / graduation letter (mock)","description":"Confirms program completion date for PGWP / 485 / Graduate Route.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample final transcript (mock)","description":"Official transcript with degree conferred date.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample study permit / visa copy (mock)","description":"Prior student visa evidence required for post-study pathways.","mimeType":"application/pdf","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000014';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample job offer / LMIA letter (mock)","description":"Employer name, role, wage, and LMIA number where required.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample employer support letter (mock)","description":"Confirms position is genuine and client meets role requirements.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample qualifications proof (mock)","description":"Degree and experience matching NOC / SOC role.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000015';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample Super Visa insurance policy (mock)","description":"1-year minimum coverage from Canadian insurer — explain to parents.","mimeType":"application/pdf","docKind":"insurance"},{"title":"Sample invitation letter from child (mock)","description":"Canadian child PR/citizen invitation with household details.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample child income proof (mock)","description":"NOA or employment letter showing LICO threshold met.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000016';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample CAS letter (mock)","description":"Confirmation of Acceptance for Studies — UKVI reference.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample IELTS UKVI TRF (mock)","description":"Secure English language test for Student Route.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample TB test certificate (mock)","description":"IOM clinic certificate if applicable.","mimeType":"application/pdf","docKind":"medical"},{"title":"Sample bank statement / 28-day rule (mock)","description":"Funds held 28 consecutive days — explain UKVI rule.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample academic transcripts (mock)","description":"Degree marks and backlogs cover note.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample consent / parental letter (mock)","description":"For students under 18 or sponsored minors.","mimeType":"application/pdf","docKind":"supporting"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000021';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample invitation / sponsor letter (mock)","description":"Host details, relationship, accommodation, and duration of stay.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample travel itinerary (mock)","description":"Flights, hotels, and day-wise plan for visitor visa credibility.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample employment / NOC letter (mock)","description":"Employer letter confirming leave, role, salary, and return to India.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample property / ties document (mock)","description":"Sale deed or tax receipt — explain home-country ties.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000022';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample marriage certificate (mock)","description":"Registered marriage proof — explain translation and notarization if needed.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample relationship timeline & photos guide (mock)","description":"Collage layout for chat logs, travel photos, and ceremony pictures.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample sponsor / undertaking letter (mock)","description":"Sponsor income, accommodation, and maintenance commitment.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample chat / communication evidence (mock)","description":"Redacted WhatsApp or email excerpts — privacy-safe specimen.","mimeType":"image/jpeg","docKind":"relationship"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000023';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample language test TRF (mock)","description":"IELTS / PTE / TOEFL layout — explain CLB or points mapping.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample ECA report (mock)","description":"WES / IQAS / ICAS credential assessment — degree equivalency page.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample employment reference letter (mock)","description":"Duties, NOC code, dates, and full-time hours on company letterhead.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample resume / CV (mock)","description":"Skilled migration format — chronological roles and NOC alignment.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample nomination / job offer letter (mock)","description":"PNP nomination or employer-backed offer where applicable.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000024';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample completion / graduation letter (mock)","description":"Confirms program completion date for PGWP / 485 / Graduate Route.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample final transcript (mock)","description":"Official transcript with degree conferred date.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample study permit / visa copy (mock)","description":"Prior student visa evidence required for post-study pathways.","mimeType":"application/pdf","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000025';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample I-20 (mock)","description":"SEVP school document — SEVIS ID and program dates.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample DS-160 confirmation (mock)","description":"Barcode page printout for interview.","mimeType":"application/pdf","docKind":"application"},{"title":"Sample IELTS / TOEFL score report (mock)","description":"English proficiency for F-1 interview prep.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample financial affidavit / I-134 (mock)","description":"Sponsor form  I-134 or bank proof for tuition + living.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample academic transcripts (mock)","description":"SEVIS-ready transcript packet.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000031';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample invitation / sponsor letter (mock)","description":"Host details, relationship, accommodation, and duration of stay.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample travel itinerary (mock)","description":"Flights, hotels, and day-wise plan for visitor visa credibility.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample employment / NOC letter (mock)","description":"Employer letter confirming leave, role, salary, and return to India.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample property / ties document (mock)","description":"Sale deed or tax receipt — explain home-country ties.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000032';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample marriage certificate (mock)","description":"Registered marriage proof — explain translation and notarization if needed.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample relationship timeline & photos guide (mock)","description":"Collage layout for chat logs, travel photos, and ceremony pictures.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample sponsor / undertaking letter (mock)","description":"Sponsor income, accommodation, and maintenance commitment.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample chat / communication evidence (mock)","description":"Redacted WhatsApp or email excerpts — privacy-safe specimen.","mimeType":"image/jpeg","docKind":"relationship"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000033';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample language test TRF (mock)","description":"IELTS / PTE / TOEFL layout — explain CLB or points mapping.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample ECA report (mock)","description":"WES / IQAS / ICAS credential assessment — degree equivalency page.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample employment reference letter (mock)","description":"Duties, NOC code, dates, and full-time hours on company letterhead.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample resume / CV (mock)","description":"Skilled migration format — chronological roles and NOC alignment.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample nomination / job offer letter (mock)","description":"PNP nomination or employer-backed offer where applicable.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000034';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample CoE (mock)","description":"Confirmation of Enrolment from CRICOS provider.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample OSHC policy (mock)","description":"Overseas Student Health Cover certificate.","mimeType":"application/pdf","docKind":"insurance"},{"title":"Sample GTE statement (mock)","description":"Genuine Temporary Entrant written statement structure.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample IELTS / PTE TRF (mock)","description":"English scores for subclass 500.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample financial capacity proof (mock)","description":"Funds for tuition + travel + 12 months living.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample academic transcripts (mock)","description":"Qualification history for GTE alignment.","mimeType":"application/pdf","docKind":"academic"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000041';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample invitation / sponsor letter (mock)","description":"Host details, relationship, accommodation, and duration of stay.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample travel itinerary (mock)","description":"Flights, hotels, and day-wise plan for visitor visa credibility.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample employment / NOC letter (mock)","description":"Employer letter confirming leave, role, salary, and return to India.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample property / ties document (mock)","description":"Sale deed or tax receipt — explain home-country ties.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000042';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample marriage certificate (mock)","description":"Registered marriage proof — explain translation and notarization if needed.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample relationship timeline & photos guide (mock)","description":"Collage layout for chat logs, travel photos, and ceremony pictures.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample sponsor / undertaking letter (mock)","description":"Sponsor income, accommodation, and maintenance commitment.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample chat / communication evidence (mock)","description":"Redacted WhatsApp or email excerpts — privacy-safe specimen.","mimeType":"image/jpeg","docKind":"relationship"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000043';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample language test TRF (mock)","description":"IELTS / PTE / TOEFL layout — explain CLB or points mapping.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample ECA report (mock)","description":"WES / IQAS / ICAS credential assessment — degree equivalency page.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample employment reference letter (mock)","description":"Duties, NOC code, dates, and full-time hours on company letterhead.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample resume / CV (mock)","description":"Skilled migration format — chronological roles and NOC alignment.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample nomination / job offer letter (mock)","description":"PNP nomination or employer-backed offer where applicable.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000044';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample completion / graduation letter (mock)","description":"Confirms program completion date for PGWP / 485 / Graduate Route.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample final transcript (mock)","description":"Official transcript with degree conferred date.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample study permit / visa copy (mock)","description":"Prior student visa evidence required for post-study pathways.","mimeType":"application/pdf","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000045';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample university admission letter (mock)","description":"German Hochschule Zulassung for national visa.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample APS certificate (mock)","description":"Academic Evaluation Centre certificate for India.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample blocked account confirmation (mock)","description":"Sperrkonto €11,904+ — explain to clients.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample IELTS / TestDaF certificate (mock)","description":"Language proof for degree program.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample CV & motivation letter (mock)","description":"German embassy standard application packet.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample travel health insurance (mock)","description":"Coverage from arrival until enrollment.","mimeType":"application/pdf","docKind":"insurance"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000051';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample invitation / sponsor letter (mock)","description":"Host details, relationship, accommodation, and duration of stay.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample travel itinerary (mock)","description":"Flights, hotels, and day-wise plan for visitor visa credibility.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample employment / NOC letter (mock)","description":"Employer letter confirming leave, role, salary, and return to India.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample property / ties document (mock)","description":"Sale deed or tax receipt — explain home-country ties.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000052';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample marriage certificate (mock)","description":"Registered marriage proof — explain translation and notarization if needed.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample relationship timeline & photos guide (mock)","description":"Collage layout for chat logs, travel photos, and ceremony pictures.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample sponsor / undertaking letter (mock)","description":"Sponsor income, accommodation, and maintenance commitment.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample chat / communication evidence (mock)","description":"Redacted WhatsApp or email excerpts — privacy-safe specimen.","mimeType":"image/jpeg","docKind":"relationship"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000053';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample language test TRF (mock)","description":"IELTS / PTE / TOEFL layout — explain CLB or points mapping.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample ECA report (mock)","description":"WES / IQAS / ICAS credential assessment — degree equivalency page.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample employment reference letter (mock)","description":"Duties, NOC code, dates, and full-time hours on company letterhead.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample resume / CV (mock)","description":"Skilled migration format — chronological roles and NOC alignment.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample nomination / job offer letter (mock)","description":"PNP nomination or employer-backed offer where applicable.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000054';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample degree / vocational certificate (mock)","description":"Recognized qualification for job seeker or opportunity pathways.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample blocked account / funds proof (mock)","description":"Financial means for Germany job seeker or opportunity card.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample CV (European format mock)","description":"Europass-style CV for German labour market orientation.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample language certificate (mock)","description":"German A1/A2 or English test where required.","mimeType":"image/jpeg","docKind":"language"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000055';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample offer of place (mock)","description":"NZ education provider acceptance letter.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample funds proof (mock)","description":"Tuition + NZD living costs per INZ calculator.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample IELTS / PTE TRF (mock)","description":"English requirement for fee-paying student visa.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample medical / chest X-ray certificate (mock)","description":"INZ-approved panel physician format.","mimeType":"application/pdf","docKind":"medical"},{"title":"Sample police certificate guide (mock)","description":"When PCC is required by residence history.","mimeType":"application/pdf","docKind":"identity"},{"title":"Sample academic transcripts (mock)","description":"Prior study evidence for pathway credibility.","mimeType":"application/pdf","docKind":"academic"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000061';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample invitation / sponsor letter (mock)","description":"Host details, relationship, accommodation, and duration of stay.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample travel itinerary (mock)","description":"Flights, hotels, and day-wise plan for visitor visa credibility.","mimeType":"application/pdf","docKind":"supporting"},{"title":"Sample employment / NOC letter (mock)","description":"Employer letter confirming leave, role, salary, and return to India.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample property / ties document (mock)","description":"Sale deed or tax receipt — explain home-country ties.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000062';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample marriage certificate (mock)","description":"Registered marriage proof — explain translation and notarization if needed.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample relationship timeline & photos guide (mock)","description":"Collage layout for chat logs, travel photos, and ceremony pictures.","mimeType":"application/pdf","docKind":"relationship"},{"title":"Sample sponsor / undertaking letter (mock)","description":"Sponsor income, accommodation, and maintenance commitment.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"},{"title":"Sample chat / communication evidence (mock)","description":"Redacted WhatsApp or email excerpts — privacy-safe specimen.","mimeType":"image/jpeg","docKind":"relationship"}],"navBucket":"visa"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000063';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample language test TRF (mock)","description":"IELTS / PTE / TOEFL layout — explain CLB or points mapping.","mimeType":"image/jpeg","docKind":"language"},{"title":"Sample ECA report (mock)","description":"WES / IQAS / ICAS credential assessment — degree equivalency page.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample employment reference letter (mock)","description":"Duties, NOC code, dates, and full-time hours on company letterhead.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample resume / CV (mock)","description":"Skilled migration format — chronological roles and NOC alignment.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample nomination / job offer letter (mock)","description":"PNP nomination or employer-backed offer where applicable.","mimeType":"application/pdf","docKind":"employment"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000064';

UPDATE public.service_library
SET academy_metadata = COALESCE(academy_metadata, '{}'::jsonb) || '{"sampleDocs":[{"title":"Sample passport bio page (mock)","description":"Show clients which pages to scan — MRZ visible, no glare, full spread.","mimeType":"image/jpeg","docKind":"identity"},{"title":"Sample completion / graduation letter (mock)","description":"Confirms program completion date for PGWP / 485 / Graduate Route.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample final transcript (mock)","description":"Official transcript with degree conferred date.","mimeType":"application/pdf","docKind":"academic"},{"title":"Sample study permit / visa copy (mock)","description":"Prior student visa evidence required for post-study pathways.","mimeType":"application/pdf","docKind":"identity"},{"title":"Sample bank statement (mock)","description":"6-month statement with name, account number, and closing balance — explain seasoning.","mimeType":"application/pdf","docKind":"financial"}],"navBucket":"immigration"}'::jsonb, updated_at = now()
WHERE id = 'b2000001-0001-4000-8000-000000000065';
